# -*- coding: utf-8 -*-
"""1A_GSE135779_CHILD_PREPROCESSING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GW6NIzajNgn20kZESACK5yBqS8BcipdA

***1) PREPROCESSING AND FILTERING***
"""

#MOUNT DRIVE

from google.colab import drive
drive.mount('/content/drive')

#DOWNLOAD PACKAGES

!pip install scanpy anndata celltypist leidenalg scrublet scipy pandas -q

#CREATE INDIVIDUAL ADATA FILES

import os
import glob
import gzip
import pandas as pd
import scanpy as sc
from scipy.io import mmread

# -------------------------------
# paths
# -------------------------------
raw_dir = "/content/drive/MyDrive/GSE135779/GSE135779_RAW"
out_dir = "/content/drive/MyDrive/GSE135779/child_individual_h5ad"
os.makedirs(out_dir, exist_ok=True)

# -------------------------------
# child GSM IDs
# -------------------------------
child_gsms = [
    "GSM4029907", "GSM4029914", "GSM4029915", "GSM4029922", "GSM4029923",
    "GSM4029930", "GSM4029931", "GSM4029936", "GSM4029937", "GSM4029938",
    "GSM4029939", "GSM4029896", "GSM4029897", "GSM4029898", "GSM4029899",
    "GSM4029900", "GSM4029901", "GSM4029902", "GSM4029903", "GSM4029904",
    "GSM4029905", "GSM4029906", "GSM4029908", "GSM4029909", "GSM4029910",
    "GSM4029911", "GSM4029912", "GSM4029913", "GSM4029916", "GSM4029917",
    "GSM4029918", "GSM4029919", "GSM4029920", "GSM4029921", "GSM4029924",
    "GSM4029925", "GSM4029926", "GSM4029927", "GSM4029928", "GSM4029929",
    "GSM4029932", "GSM4029933", "GSM4029934", "GSM4029935"
]

# -------------------------------
# helper functions
# -------------------------------
def find_one_file(patterns):
    """Return first existing match across a list of glob patterns."""
    for pattern in patterns:
        hits = glob.glob(pattern)
        if hits:
            return hits[0]
    return None

def read_table_auto(path, header=None):
    """Read .tsv or .tsv.gz."""
    return pd.read_csv(path, sep="\t", header=header)

def make_unique(names):
    """Simple replacement for older pandas ParserBase dedup."""
    seen = {}
    out = []
    for x in names:
        x = "NA" if pd.isna(x) or str(x).strip() == "" else str(x)
        if x not in seen:
            seen[x] = 0
            out.append(x)
        else:
            seen[x] += 1
            out.append(f"{x}-{seen[x]}")
    return pd.Index(out)

# -------------------------------
# load shared genes file
# -------------------------------
genes_path = os.path.join(raw_dir, "GSE135779_genes.tsv.gz")
genes = read_table_auto(genes_path, header=None)

print("Genes file shape:", genes.shape)

# Common formats:
# col0 = Ensembl/gene_id
# col1 = gene_symbol
if genes.shape[1] >= 2:
    gene_ids = genes.iloc[:, 0].astype(str).values
    gene_symbols = genes.iloc[:, 1].astype(str).values
else:
    gene_ids = genes.iloc[:, 0].astype(str).values
    gene_symbols = genes.iloc[:, 0].astype(str).values

gene_symbols = make_unique(gene_symbols)

# -------------------------------
# create one h5ad per child GSM
# -------------------------------
made_files = []
missing = []

for gsm in child_gsms:
    # find matrix and barcode files for this GSM
    matrix_path = find_one_file([
        os.path.join(raw_dir, f"{gsm}_*_matrix.mtx.gz"),
        os.path.join(raw_dir, f"{gsm}_*_matrix.mtx")
    ])

    barcodes_path = find_one_file([
        os.path.join(raw_dir, f"{gsm}_*_barcodes.tsv.gz"),
        os.path.join(raw_dir, f"{gsm}_*_barcodes.tsv")
    ])

    if matrix_path is None or barcodes_path is None:
        missing.append((gsm, matrix_path, barcodes_path))
        print(f"Skipping {gsm}: missing file(s)")
        continue

    # sample name = filename stem before "_matrix"
    # example: GSM4029907_JB17010
    base = os.path.basename(matrix_path)
    sample_name = base.replace("_matrix.mtx.gz", "").replace("_matrix.mtx", "")

    print(f"Processing {sample_name}...")

    # read sparse matrix
    X = mmread(matrix_path).tocsr()

    # GEO matrices are usually genes x cells -> transpose to cells x genes
    # we will confirm against barcode and gene lengths
    barcodes = read_table_auto(barcodes_path, header=None).iloc[:, 0].astype(str).values

    if X.shape[0] == len(gene_symbols) and X.shape[1] == len(barcodes):
        X = X.T   # convert to cells x genes
    elif X.shape[0] == len(barcodes) and X.shape[1] == len(gene_symbols):
        pass      # already cells x genes
    else:
        raise ValueError(
            f"{sample_name}: matrix shape {X.shape} does not match "
            f"{len(gene_symbols)} genes and {len(barcodes)} barcodes"
        )

    # build AnnData
    adata = sc.AnnData(X=X)

    # unique cell names: sample_barcode
    adata.obs_names = [f"{sample_name}_{bc}" for bc in barcodes]
    adata.var_names = gene_symbols

    # store extra gene/sample metadata
    adata.var["gene_ids"] = gene_ids
    adata.var["gene_symbols"] = adata.var_names
    adata.obs["gsm_id"] = gsm
    adata.obs["sample"] = sample_name

    # save
    out_path = os.path.join(out_dir, f"{sample_name}.h5ad")
    adata.write_h5ad(out_path)
    made_files.append(out_path)

print("\nDone.")
print(f"Created {len(made_files)} h5ad files.")
if missing:
    print("\nMissing files for these GSMs:")
    for item in missing:
#        print(item)

#FILTER CELLS AND GENES TO MAKE INDIVIDUAL FILES BEFORE COMBINING -- RAM

import os
import glob
import scanpy as sc

in_dir = "/content/drive/MyDrive/GSE135779/child_individual_h5ad"
out_dir = "/content/drive/MyDrive/GSE135779/child_individual_h5ad_filtered"
os.makedirs(out_dir, exist_ok=True)

h5ad_files = sorted(glob.glob(os.path.join(in_dir, "*.h5ad")))
print(f"Found {len(h5ad_files)} files")

for f in h5ad_files:
    sample_name = os.path.basename(f)
    print(f"\nProcessing {sample_name}")

    adata = sc.read_h5ad(f)
    print("  original shape:", adata.shape)

    # basic per-cell QC metric
    adata.var["mt"] = adata.var_names.str.upper().str.startswith("MT-")
    sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], inplace=True)

    # filter cells and genes
    sc.pp.filter_cells(adata, min_genes=200)
    sc.pp.filter_genes(adata, min_cells=3)

    # very mild mitochondrial filtering
    adata = adata[adata.obs["pct_counts_mt"] < 25].copy()

    print("  filtered shape:", adata.shape)

    out_path = os.path.join(out_dir, sample_name)
    adata.write_h5ad(out_path)
    print("  saved:", out_path)

# COMBINE IN H5AD IN CHUNKS

import os
import glob
import scanpy as sc
import anndata as ad

in_dir = "/content/drive/MyDrive/GSE135779/child_individual_h5ad_filtered"
chunk_dir = "/content/drive/MyDrive/GSE135779/child_chunks"
os.makedirs(chunk_dir, exist_ok=True)

files = sorted(glob.glob(os.path.join(in_dir, "*.h5ad")))

chunk_size = 5

for i in range(0, len(files), chunk_size):
    chunk_files = files[i:i+chunk_size]
    print(f"\nProcessing chunk {i//chunk_size + 1}")

    adatas = [sc.read_h5ad(f) for f in chunk_files]

    adata_chunk = ad.concat(
        adatas,
        axis=0,
        join="inner",
        merge="same",
        index_unique=None
    )

    out_path = os.path.join(chunk_dir, f"chunk_{i//chunk_size}.h5ad")
    adata_chunk.write_h5ad(out_path)

    print("Saved:", out_path, adata_chunk.shape)

    del adatas, adata_chunk

# SCRUBLET — CHILD CHUNKS DOUBLET FILTERING

import scanpy as sc
import scrublet as scr
import numpy as np
from scipy import sparse
import os

input_dir = "/content/drive/MyDrive/GSE135779/child_chunks"
output_dir = "/content/drive/MyDrive/GSE135779/child_chunks_nodoublet"

os.makedirs(output_dir, exist_ok=True)

for file in sorted(os.listdir(input_dir)):
    if file.startswith("chunk_") and file.endswith(".h5ad"):

        input_path = os.path.join(input_dir, file)
        output_path = os.path.join(output_dir, file)

        print("\n==============================")
        print("Processing:", file)

        adata = sc.read_h5ad(input_path)
        print("Original shape:", adata.shape)

        counts_matrix = adata.X
        if sparse.issparse(counts_matrix):
            counts_matrix = counts_matrix.tocsc()
        else:
            counts_matrix = np.array(counts_matrix)

        scrub = scr.Scrublet(
            counts_matrix,
            expected_doublet_rate=0.06
        )

        doublet_scores, predicted_doublets = scrub.scrub_doublets(
            min_counts=2,
            min_cells=3,
            min_gene_variability_pctl=85,
            n_prin_comps=30
        )

        adata.obs["doublet_score"] = doublet_scores
        adata.obs["predicted_doublet"] = predicted_doublets.astype(bool)

        print("Doublet counts:")
        print(adata.obs["predicted_doublet"].value_counts())
        print("Doublet fraction:", adata.obs["predicted_doublet"].mean())

        adata_clean = adata[~adata.obs["predicted_doublet"]].copy()
        print("After removal:", adata_clean.shape)

        adata_clean.write(output_path)
        print("Saved:", output_path)

print("\nDONE: child chunk doublet filtering complete.")

import os
import glob
import gc
import scanpy as sc
import anndata as ad

chunk_dir = "/content/drive/MyDrive/GSE135779/child_chunks_nodoublet"
superchunk_dir = "/content/drive/MyDrive/GSE135779/child_superchunks"
os.makedirs(superchunk_dir, exist_ok=True)

chunk_files = sorted(glob.glob(os.path.join(chunk_dir, "*.h5ad")))
print(f"Found {len(chunk_files)} chunk files")

group_size = 2   # safer than 3 if RAM is tight

for group_idx, start in enumerate(range(0, len(chunk_files), group_size)):
    group = chunk_files[start:start + group_size]
    out_path = os.path.join(superchunk_dir, f"superchunk_{group_idx:02d}.h5ad")

    print(f"\nCreating {os.path.basename(out_path)} from:")
    for f in group:
        print("  ", os.path.basename(f))

    adata_merged = sc.read_h5ad(group[0])

    for f in group[1:]:
        adata_next = sc.read_h5ad(f)

        adata_merged = ad.concat(
            [adata_merged, adata_next],
            axis=0,
            join="inner",
            merge="same",
            index_unique=None
        )
        adata_merged.obs_names_make_unique()

        del adata_next
        gc.collect()

    print("Superchunk shape:", adata_merged.shape)
    adata_merged.write_h5ad(out_path)
    print("Saved:", out_path)

    del adata_merged
    gc.collect()

print("\nDone creating superchunks.")
print(sorted(glob.glob(os.path.join(superchunk_dir, "*.h5ad"))))

# COMBINE SUPER CHUNKS

import os
import glob
import gc
import scanpy as sc
import anndata as ad

superchunk_dir = "/content/drive/MyDrive/GSE135779/child_superchunks"
final_path = "/content/drive/MyDrive/GSE135779/adata_child_combined.h5ad"

superchunk_files = sorted(glob.glob(os.path.join(superchunk_dir, "*.h5ad")))
print(f"Found {len(superchunk_files)} superchunk files")

if len(superchunk_files) == 0:
    raise ValueError("No superchunk files found.")

adata_child = sc.read_h5ad(superchunk_files[0])
print("Loaded first superchunk:", os.path.basename(superchunk_files[0]), adata_child.shape)

for f in superchunk_files[1:]:
    print("Adding superchunk:", os.path.basename(f))
    adata_next = sc.read_h5ad(f)

    adata_child = ad.concat(
        [adata_child, adata_next],
        axis=0,
        join="inner",
        merge="same",
        index_unique=None
    )
    adata_child.obs_names_make_unique()

    print("Current shape:", adata_child.shape)

    del adata_next
    gc.collect()

adata_child.write_h5ad(final_path)
print("Saved final child file:", final_path)
print(adata_child)

# SANITY CHECK

import scanpy as sc
import pandas as pd
from scipy import sparse

path = "/content/drive/MyDrive/GSE135779/adata_child_combined.h5ad"

adata = sc.read_h5ad(path)
print("Loaded:", adata)
print("Shape:", adata.shape)

print("\n--- BASIC STRUCTURE ---")
print("obs columns:", list(adata.obs.columns))
print("var columns:", list(adata.var.columns))
print("uns keys:", list(adata.uns.keys()))
print("obsm keys:", list(adata.obsm.keys()))
print("layers keys:", list(adata.layers.keys()))

print("\n--- MATRIX TYPE ---")
print("X type:", type(adata.X))
print("Is sparse:", sparse.issparse(adata.X))
print("dtype:", adata.X.dtype)

print("\n--- OBS NAMES ---")
print("obs unique:", adata.obs_names.is_unique)
print("first 5 obs_names:", list(adata.obs_names[:5]))

print("\n--- VAR NAMES ---")
print("var unique:", adata.var_names.is_unique)
print("first 20 var_names:", list(adata.var_names[:20]))
print("ENSG-like genes among first 100 var_names:",
      sum(str(x).startswith("ENSG") for x in adata.var_names[:100]))

print("\n--- SAMPLE INFO ---")
if "sample" in adata.obs.columns:
    print("number of samples:", adata.obs["sample"].nunique())
    print(adata.obs["sample"].value_counts().head(10))
else:
    print("WARNING: 'sample' column missing")

if "gsm_id" in adata.obs.columns:
    print("\nnumber of GSM IDs:", adata.obs["gsm_id"].nunique())
    print(adata.obs["gsm_id"].value_counts().head(10))
else:
    print("WARNING: 'gsm_id' column missing")

print("\n--- MISSING VALUES ---")
print("obs missing total:", int(adata.obs.isna().sum().sum()))
print("var missing total:", int(adata.var.isna().sum().sum()))

print("\n--- DUPLICATE / ZERO CHECKS ---")
if sparse.issparse(adata.X):
    row_sums = adata.X.sum(axis=1)
    col_sums = adata.X.sum(axis=0)
    row_sums = row_sums.A1 if hasattr(row_sums, "A1") else row_sums
    col_sums = col_sums.A1 if hasattr(col_sums, "A1") else col_sums
else:
    row_sums = adata.X.sum(axis=1)
    col_sums = adata.X.sum(axis=0)

print("cells with zero total counts:", int((row_sums == 0).sum()))
print("genes with zero total counts:", int((col_sums == 0).sum()))

print("\n--- OPTIONAL QC SUMMARY ---")
if "pct_counts_mt" in adata.obs.columns:
    print(adata.obs["pct_counts_mt"].describe())
else:
    print("pct_counts_mt not present")

if "n_genes_by_counts" in adata.obs.columns:
    print(adata.obs["n_genes_by_counts"].describe())
else:
    print("n_genes_by_counts not present")

print("\n--- QUICK SANITY FLAGS ---")
flags = []

if not adata.obs_names.is_unique:
    flags.append("obs_names are not unique")
if not adata.var_names.is_unique:
    flags.append("var_names are not unique")
if "sample" not in adata.obs.columns:
    flags.append("missing sample column")
if "gsm_id" not in adata.obs.columns:
    flags.append("missing gsm_id column")
if (row_sums == 0).sum() > 0:
    flags.append("there are cells with zero counts")
if (col_sums == 0).sum() > 0:
    flags.append("there are genes with zero counts")

if len(flags) == 0:
    print("No obvious structural problems found.")
else:
    print("Warnings:")
    for f in flags:
        print("-", f)

import scanpy as sc
import pandas as pd
from scipy import sparse

in_path = "/content/drive/MyDrive/GSE135779/adata_child_combined.h5ad"
work_path = "/content/drive/MyDrive/GSE135779/adata_child_working.h5ad"

adata = sc.read_h5ad(in_path)
print("Loaded:", adata)

# keep only obs columns you actually need right now
keep_obs = ["gsm_id", "sample"]
adata.obs = adata.obs[keep_obs].copy()

# keep only minimal var metadata
keep_var = ["gene_ids"]
adata.var = adata.var[keep_var].copy()

# keep matrix sparse and lighter
if not sparse.issparse(adata.X):
    adata.X = sparse.csr_matrix(adata.X)

adata.X = adata.X.astype("float32")

print("Working object:", adata)
adata.write_h5ad(work_path)
print("Saved:", work_path)



import scanpy as sc
from scipy import sparse

in_path = "/content/drive/MyDrive/GSE135779/adata_child_combined.h5ad"
norm_path = "/content/drive/MyDrive/GSE135779/adata_child_combined_norm.h5ad"

adata = sc.read_h5ad(in_path)
print("Loaded:", adata)

# reduce memory footprint
if not sparse.issparse(adata.X):
    adata.X = sparse.csr_matrix(adata.X)

adata.X = adata.X.astype("float32")

# normalize
sc.pp.normalize_total(adata, target_sum=1e4)

print("Normalized:", adata)

adata.write_h5ad(norm_path)
print("Saved to:", norm_path)

import scanpy as sc

in_path = "/content/drive/MyDrive/GSE135779/adata_child_combined_norm.h5ad"
log_path = "/content/drive/MyDrive/GSE135779/adata_child_combined_log1p.h5ad"

adata = sc.read_h5ad(in_path)
print("Loaded:", adata)

sc.pp.log1p(adata, chunked=True, chunk_size=2000)

print("Log1p done:", adata)

adata.write_h5ad(log_path)
print("Saved to:", log_path)

import scanpy as sc

in_path = "/content/drive/MyDrive/GSE135779/adata_child_combined_log1p.h5ad"
hvg_path = "/content/drive/MyDrive/GSE135779/adata_child_combined_log1p_hvg.h5ad"

adata = sc.read_h5ad(in_path)
print("Loaded:", adata)

sc.pp.highly_variable_genes(
    adata,
    n_top_genes=2000,
    flavor="seurat"
)

print("Highly variable genes:", int(adata.var["highly_variable"].sum()))
adata.write_h5ad(hvg_path)
print("Saved:", hvg_path)

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adata_child_combined_log1p_hvg.h5ad"
)

print("Loaded:", adata)
print("HVGs:", int(adata.var["highly_variable"].sum()))

# PCA directly on HVGs, no scaling
sc.tl.pca(adata, svd_solver="arpack", use_highly_variable=True)

# neighbors + UMAP
sc.pp.neighbors(adata, n_neighbors=15, n_pcs=30)
sc.tl.umap(adata)

# Leiden at multiple resolutions
resolutions = [0.2, 0.5, 0.8]
for res in resolutions:
    key = f"leiden_res_{res}"
    sc.tl.leiden(adata, resolution=res, key_added=key)
    print(key, "->", adata.obs[key].nunique(), "clusters")

# save
out_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_child_processed_multi_leiden.h5ad"
adata.write_h5ad(out_path)
print("Saved:", out_path)

sc.pl.umap(
    adata,
    color=["leiden_res_0.2", "leiden_res_0.5", "leiden_res_0.8"],
    wspace=0.4
)

sc.pl.umap(
    adata,
    color=["leiden_res_0.8"],
    wspace=0.4
)

adata.write_h5ad("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_processed_selected_leiden.h5ad")

adata.obs["leiden"] = adata.obs["leiden_res_0.8"]

adata.write_h5ad("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_processed_leiden08.h5ad")

"""***2) CELL TYPE LABELLING***"""

sc.tl.rank_genes_groups(adata, groupby="leiden", method="wilcoxon")
sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False)

import scanpy as sc
adata = sc.read_h5ad("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_processed_leiden08.h5ad")
adata.obs["cell_type"] = adata.obs["leiden"].map(cell_type_map)

# CELL TYPE MAP

cell_type_map = {
    "0": "Classical monocytes",
    "1": "Low-quality / ribosomal",
    "2": "B cells",
    "3": "Low-quality / ribosomal",
    "4": "Cytotoxic T cells",
    "5": "CD4 T cells",
    "6": "IFN-stimulated T cells",
    "7": "CD8 T cells / Low-quality / ribosomal",
    "8": "NK cells",
    "9": "CD8 T cells",
    "10": "IFN-stimulated monocytes",
    "11": "Classical monocytes",
    "12": "Classical monocytes",
    "13": "cDC",
    "14": "Plasma cells",
    "15": "Erythrocytes",
    "16": "B cells",
    "17": "cDC",
    "18": "Platelets"
}

sc.pl.umap(adata, color="cell_type", legend_loc="on data")

bad_types = [
    "Low-quality / ribosomal",
    "Erythroids",
    "Erythrocytes",
    "Platelets",
    "CD8 T cells / Low-quality / ribosomal",
    "Activated / stress-response cells"
]

adata_clean = adata[~adata.obs["cell_type"].isin(bad_types)].copy()

print("Before:", adata.shape)
print("After:", adata_clean.shape)
print(adata_clean.obs["cell_type"].value_counts())

sc.pl.umap(adata_clean, color="cell_type", legend_loc="on data")

import scanpy as sc
import matplotlib.pyplot as plt
import pandas as pd

adata.obs["leiden_res_0.8"] = adata.obs["leiden_res_0.8"].astype(str)

# UMAP with cluster numbers on the plot
sc.pl.umap(
    adata,
    color="leiden_res_0.8",
    legend_loc="on data",
    legend_fontsize=12,
    legend_fontweight="bold",
    size=3,
    frameon=True,
    title="Leiden clusters"
)

# print number legend as a clean table
legend_df = pd.DataFrame({
    "cluster": list(cell_type_map.keys()),
    "cell_type": list(cell_type_map.values())
}).sort_values("cluster", key=lambda x: x.astype(int))

legend_df

adata_clean.write_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_final_liana.h5ad"
)

import scanpy as sc
import numpy as np

adata = sc.read_h5ad("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_processed_leiden08.h5ad")

# subsample ~50k cells
idx = np.random.choice(adata.n_obs, 50000, replace=False)
adata_sub = adata[idx].copy()

print("Subsample:", adata_sub)

import scanpy as sc
import pandas as pd
import matplotlib.pyplot as plt

# Load AnnData
adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_final_liana.h5ad"
)

# Lists
healthy_samples = [
    "GSM4029907_JB17010",
    "GSM4029914_JB17017",
    "GSM4029915_JB17018",
    "GSM4029922_JB18069",
    "GSM4029923_JB18070",
    "GSM4029930_JB18077",
    "GSM4029931_JB18078",
    "GSM4029936_JB18085",
    "GSM4029937_JB18086",
    "GSM4029938_JB18083",
    "GSM4029939_JB18084",
]

sick_samples = [
    "GSM4029896_JB17001","GSM4029897_JB17002","GSM4029898_JB17003",
    "GSM4029899_JB17004","GSM4029900_JB17005","GSM4029901_JB17006",
    "GSM4029902_JB17007","GSM4029903_JB17008","GSM4029904_JB17015",
    "GSM4029905_JB17016","GSM4029906_JB17014","GSM4029908_JB17019",
    "GSM4029909_JB17020","GSM4029910_JB17021","GSM4029911_JB17022",
    "GSM4029912_JB17023","GSM4029913_JB17024","GSM4029916_JB18063",
    "GSM4029917_JB18064","GSM4029918_JB18065","GSM4029919_JB18066",
    "GSM4029920_JB18067","GSM4029921_JB18068","GSM4029924_JB18071",
    "GSM4029925_JB18072","GSM4029926_JB18073","GSM4029927_JB18074",
    "GSM4029928_JB18075","GSM4029929_JB18076","GSM4029932_JB18079",
    "GSM4029933_JB18080","GSM4029934_JB18081","GSM4029935_JB18082"
]

# ----- CHANGE "sample" if needed -----
sample_col = "sample"

# Create condition labels
adata.obs["condition"] = "Unknown"

adata.obs.loc[
    adata.obs[sample_col].isin(healthy_samples),
    "condition"
] = "Healthy"

adata.obs.loc[
    adata.obs[sample_col].isin(sick_samples),
    "condition"
] = "Sick"

# Remove unknown cells if any
adata = adata[adata.obs["condition"] != "Unknown"].copy()

# Compute UMAP if not already present
if "X_umap" not in adata.obsm:
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)

    sc.pp.highly_variable_genes(
        adata,
        n_top_genes=3000
    )

    adata = adata[:, adata.var.highly_variable].copy()

    sc.pp.scale(adata, max_value=10)
    sc.tl.pca(adata)

    sc.pp.neighbors(
        adata,
        n_neighbors=15,
        n_pcs=30
    )

    sc.tl.umap(adata)

# Plot
sc.pl.umap(
    adata,
    color="condition",
    title="Healthy vs Sick UMAP",
    frameon=False,
    size=20
)

# CELL TYPIST

import celltypist

predictions = celltypist.annotate(
    adata_sub,
    model="Immune_All_Low.pkl",
    majority_voting=True
)

adata_sub.obs = adata_sub.obs.join(predictions.predicted_labels)

import pandas as pd

pd.crosstab(
    adata_sub.obs["leiden_res_0.8"],
    adata_sub.obs["majority_voting"],
    normalize="index"
).round(2)

"""***3) SPLITTING***"""

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_final_liana.h5ad"
)

healthy_samples = [
    "GSM4029907_JB17010",
    "GSM4029914_JB17017",
    "GSM4029915_JB17018",
    "GSM4029922_JB18069",
    "GSM4029923_JB18070",
    "GSM4029930_JB18077",
    "GSM4029931_JB18078",
    "GSM4029936_JB18085",
    "GSM4029937_JB18086",
    "GSM4029938_JB18083",
    "GSM4029939_JB18084",
]

sick_samples = [
    "GSM4029896_JB17001",
    "GSM4029897_JB17002",
    "GSM4029898_JB17003",
    "GSM4029899_JB17004",
    "GSM4029900_JB17005",
    "GSM4029901_JB17006",
    "GSM4029902_JB17007",
    "GSM4029903_JB17008",
    "GSM4029904_JB17015",
    "GSM4029905_JB17016",
    "GSM4029906_JB17014",
    "GSM4029908_JB17019",
    "GSM4029909_JB17020",
    "GSM4029910_JB17021",
    "GSM4029911_JB17022",
    "GSM4029912_JB17023",
    "GSM4029913_JB17024",
    "GSM4029916_JB18063",
    "GSM4029917_JB18064",
    "GSM4029918_JB18065",
    "GSM4029919_JB18066",
    "GSM4029920_JB18067",
    "GSM4029921_JB18068",
    "GSM4029924_JB18071",
    "GSM4029925_JB18072",
    "GSM4029926_JB18073",
    "GSM4029927_JB18074",
    "GSM4029928_JB18075",
    "GSM4029929_JB18076",
    "GSM4029932_JB18079",
    "GSM4029933_JB18080",
    "GSM4029934_JB18081",
    "GSM4029935_JB18082",
]

adata.obs["condition"] = "unknown"
adata.obs.loc[adata.obs["sample"].isin(healthy_samples), "condition"] = "healthy"
adata.obs.loc[adata.obs["sample"].isin(sick_samples), "condition"] = "sick"

print(adata.obs["condition"].value_counts())
print(adata.obs[["sample", "condition"]].drop_duplicates().sort_values("sample"))

adata_child_healthy = adata[adata.obs["condition"] == "healthy"].copy()
adata_child_sick = adata[adata.obs["condition"] == "sick"].copy()

print("Healthy:", adata_child_healthy)
print("Sick:", adata_child_sick)

healthy_path = "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_healthy_liana.h5ad"
sick_path = "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_sick_liana.h5ad"

adata_child_healthy.write_h5ad(healthy_path)
adata_child_sick.write_h5ad(sick_path)

print("Saved healthy:", healthy_path)
print("Saved sick:", sick_path)

import scanpy as sc
import pandas as pd
from pathlib import Path

files = {
    "child_sick": Path("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_sick_liana.h5ad"),
    "child_healthy": Path("/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_healthy_liana.h5ad"),
}

for name, path in files.items():
    print("=" * 80)
    print(name)
    print(path)

    adata = sc.read_h5ad(path)

    if "cell_type" not in adata.obs.columns:
        print("No 'cell_type' column found.")
        print("Available obs columns:")
        print(adata.obs.columns.tolist())
        continue

    cell_type_counts = (
        adata.obs["cell_type"]
        .value_counts(dropna=False)
        .reset_index()
    )

    cell_type_counts.columns = ["cell_type", "n_cells"]

    print("\nUnique cell types:")
    print(cell_type_counts["cell_type"].tolist())

    print("\nCell type counts:")
    display(cell_type_counts)

    print("\nTotal cells:", adata.n_obs)

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_sick_liana.h5ad"
)

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_healthy_liana.h5ad"
)

print(adata.obs["cell_type"].unique())

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/child_individual_h5ad/adata_child_final_liana.h5ad"
)

# Fix any stale capitalization in cell_type
adata.obs["cell_type"] = adata.obs["cell_type"].str.replace(
    "CD8 T Cells", "CD8 T cells", regex=False
)

# Confirm fix
print(adata.obs["cell_type"].unique())