# -*- coding: utf-8 -*-
"""1B_GSE135779_ADULT_PREPROCESSING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgUTyDeCwy4mReW1HbjQH7vCKf5Qr96r

***1) PREPROCESSING AND FILTERING***
"""

#MOUNT DRIVE

from google.colab import drive
drive.mount('/content/drive')

#DOWNLOAD PACKAGES

!pip install scanpy anndata scipy scrublet celltypist leidenalg pandas -q

#CREATE INDIVIDUAL ADATA FILES

import os
import glob
import gzip
import pandas as pd
import scanpy as sc
from scipy.io import mmread

# -------------------------------
# paths
# -------------------------------
raw_dir = "/content/drive/MyDrive/GSE135779/GSE135779_RAW"
out_dir = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad"
os.makedirs(out_dir, exist_ok=True)

# -------------------------------
# adult GSM IDs
# -------------------------------
adult_gsms = [
    "GSM4029950", "GSM4029951", "GSM4029952", "GSM4029943", "GSM4029944",
    "GSM4029945", "GSM4029946", "GSM4029940", "GSM4029942", "GSM4029947",
    "GSM4029948", "GSM4029949"
]

# -------------------------------
# helper functions
# -------------------------------
def find_one_file(patterns):
    """Return first existing match across a list of glob patterns."""
    for pattern in patterns:
        hits = glob.glob(pattern)
        if hits:
            return hits[0]
    return None

def read_table_auto(path, header=None):
    """Read .tsv or .tsv.gz."""
    return pd.read_csv(path, sep="\t", header=header)

def make_unique(names):
    """Simple replacement for older pandas ParserBase dedup."""
    seen = {}
    out = []
    for x in names:
        x = "NA" if pd.isna(x) or str(x).strip() == "" else str(x)
        if x not in seen:
            seen[x] = 0
            out.append(x)
        else:
            seen[x] += 1
            out.append(f"{x}-{seen[x]}")
    return pd.Index(out)

# -------------------------------
# load shared genes file
# -------------------------------
genes_path = os.path.join(raw_dir, "GSE135779_genes.tsv.gz")
genes = read_table_auto(genes_path, header=None)

print("Genes file shape:", genes.shape)

# Common formats:
# col0 = Ensembl/gene_id
# col1 = gene_symbol
if genes.shape[1] >= 2:
    gene_ids = genes.iloc[:, 0].astype(str).values
    gene_symbols = genes.iloc[:, 1].astype(str).values
else:
    gene_ids = genes.iloc[:, 0].astype(str).values
    gene_symbols = genes.iloc[:, 0].astype(str).values

gene_symbols = make_unique(gene_symbols)

# -------------------------------
# create one h5ad per adult GSM
# -------------------------------
made_files = []
missing = []

for gsm in adult_gsms:
    # find matrix and barcode files for this GSM
    matrix_path = find_one_file([
        os.path.join(raw_dir, f"{gsm}_*_matrix.mtx.gz"),
        os.path.join(raw_dir, f"{gsm}_*_matrix.mtx")
    ])

    barcodes_path = find_one_file([
        os.path.join(raw_dir, f"{gsm}_*_barcodes.tsv.gz"),
        os.path.join(raw_dir, f"{gsm}_*_barcodes.tsv")
    ])

    if matrix_path is None or barcodes_path is None:
        missing.append((gsm, matrix_path, barcodes_path))
        print(f"Skipping {gsm}: missing file(s)")
        continue

    # sample name = filename stem before "_matrix"
    # example: GSM4029907_JB17010
    base = os.path.basename(matrix_path)
    sample_name = base.replace("_matrix.mtx.gz", "").replace("_matrix.mtx", "")

    print(f"Processing {sample_name}...")

    # read sparse matrix
    X = mmread(matrix_path).tocsr()

    # GEO matrices are usually genes x cells -> transpose to cells x genes
    # we will confirm against barcode and gene lengths
    barcodes = read_table_auto(barcodes_path, header=None).iloc[:, 0].astype(str).values

    if X.shape[0] == len(gene_symbols) and X.shape[1] == len(barcodes):
        X = X.T   # convert to cells x genes
    elif X.shape[0] == len(barcodes) and X.shape[1] == len(gene_symbols):
        pass      # already cells x genes
    else:
        raise ValueError(
            f"{sample_name}: matrix shape {X.shape} does not match "
            f"{len(gene_symbols)} genes and {len(barcodes)} barcodes"
        )

    # build AnnData
    adata = sc.AnnData(X=X)

    # unique cell names: sample_barcode
    adata.obs_names = [f"{sample_name}_{bc}" for bc in barcodes]
    adata.var_names = gene_symbols

    # store extra gene/sample metadata
    adata.var["gene_ids"] = gene_ids
    adata.var["gene_symbols"] = adata.var_names
    adata.obs["gsm_id"] = gsm
    adata.obs["sample"] = sample_name

    # save
    out_path = os.path.join(out_dir, f"{sample_name}.h5ad")
    adata.write_h5ad(out_path)
    made_files.append(out_path)

print("\nDone.")
print(f"Created {len(made_files)} h5ad files.")
if missing:
    print("\nMissing files for these GSMs:")
    for item in missing:
        print(item)

# SCRUBLET — BATCH DOUBLET FILTERING PER GSM FILE

import scanpy as sc
import scrublet as scr
import numpy as np
from scipy import sparse
import os

# ===== PATHS =====
input_dir = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad"
output_dir = "/content/drive/MyDrive/GSE135779/adult_individual_nodoublet_h5ad"

os.makedirs(output_dir, exist_ok=True)

# ===== LOOP THROUGH FILES =====
for file in os.listdir(input_dir):

    if file.startswith("GSM") and file.endswith(".h5ad"):

        input_path = os.path.join(input_dir, file)
        output_path = os.path.join(output_dir, file)

        print("\n==============================")
        print(f"Processing: {file}")

        # ===== LOAD =====
        adata = sc.read_h5ad(input_path)
        print("Original shape:", adata.shape)

        # ===== CHECK RAW COUNTS =====
        if np.issubdtype(adata.X.dtype, np.floating):
            print("⚠️ WARNING: Data may already be normalized/logged")

        # ===== PREP MATRIX =====
        counts_matrix = adata.X
        if sparse.issparse(counts_matrix):
            counts_matrix = counts_matrix.tocsc()
        else:
            counts_matrix = np.array(counts_matrix)

        # ===== RUN SCRUBLET =====
        scrub = scr.Scrublet(counts_matrix, expected_doublet_rate=0.06)

        doublet_scores, predicted_doublets = scrub.scrub_doublets(
            min_counts=2,
            min_cells=3,
            min_gene_variability_pctl=85,
            n_prin_comps=30
        )

        # ===== STORE =====
        adata.obs["doublet_score"] = doublet_scores
        adata.obs["predicted_doublet"] = predicted_doublets.astype(bool)

        print("Doublet counts:")
        print(adata.obs["predicted_doublet"].value_counts())
        print("Doublet fraction:", adata.obs["predicted_doublet"].mean())

        # ===== FILTER =====
        adata_clean = adata[~adata.obs["predicted_doublet"]].copy()
        print("After removal:", adata_clean.shape)

        # ===== SAVE =====
        adata_clean.write(output_path)
        print(f"Saved to: {output_path}")

print("\n✅ DONE: All GSM files processed")

#COMBINE H5AD FILES INTO SINGLE ONE

import os
import glob
import scanpy as sc
import anndata as ad

# -------------------------------
# paths
# -------------------------------
in_dir = "/content/drive/MyDrive/GSE135779/adult_individual_nodoublet_h5ad"
out_path = "/content/drive/MyDrive/GSE135779/adata_adult_combined.h5ad"

# -------------------------------
# find all adult h5ad files
# -------------------------------
h5ad_files = sorted(glob.glob(os.path.join(in_dir, "*.h5ad")))

print(f"Found {len(h5ad_files)} child h5ad files")
for f in h5ad_files[:5]:
    print(" ", os.path.basename(f))

# -------------------------------
# read them in
# -------------------------------
adatas = []
for f in h5ad_files:
    adata = sc.read_h5ad(f)

    # make sure sample column exists
    if "sample" not in adata.obs.columns:
        sample_name = os.path.basename(f).replace(".h5ad", "")
        adata.obs["sample"] = sample_name

    adatas.append(adata)

print(f"Loaded {len(adatas)} AnnData objects")

# -------------------------------
# combine
# -------------------------------
adata_adult = ad.concat(
    adatas,
    axis=0,                # stack cells
    join="outer",          # keep all genes if anything differs
    merge="same",
    label="batch_file",
    keys=[os.path.basename(f).replace(".h5ad", "") for f in h5ad_files],
    index_unique=None
)

# -------------------------------
# cleanup
# -------------------------------
# make obs_names unique just in case
adata_adult.obs_names_make_unique()

print(adata_adult)
print(adata_adult.obs.head())
print(adata_adult.var.head())

# -------------------------------
# save
# -------------------------------
adata_adult.write_h5ad(out_path)
print(f"Saved combined adult AnnData to:\n{out_path}")

import scanpy as sc

adata = sc.read_h5ad("/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_combined.h5ad")

print("Original shape:", adata.shape)

# same QC metric calculation as child
adata.var["mt"] = adata.var_names.str.upper().str.startswith("MT-")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], inplace=True)

# same filtering as child
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

print("Filtered shape:", adata.shape)

out_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_combined_filtered.h5ad"
adata.write_h5ad(out_path)
print("Saved:", out_path)

import scanpy as sc

# load filtered object
adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_combined_filtered.h5ad"
)

print("Loaded:", adata)

# keep raw counts before normalization
adata.layers["counts"] = adata.X.copy()

# normalize and log transform
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# save log-normalized matrix in .raw
adata.raw = adata

# highly variable genes
sc.pp.highly_variable_genes(
    adata,
    n_top_genes=2000,
    flavor="seurat"
)

print("Done")
print(adata)
print("Highly variable genes:", int(adata.var["highly_variable"].sum()))

out_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_combined_filtered2.h5ad"
adata.write_h5ad(out_path)

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_combined_filtered2.h5ad"
)

print("Loaded:", adata)
print("HVGs:", int(adata.var["highly_variable"].sum()))

# PCA directly on HVGs, no scaling
sc.tl.pca(adata, svd_solver="arpack", use_highly_variable=True)

# neighbors + UMAP
sc.pp.neighbors(adata, n_neighbors=15, n_pcs=30)
sc.tl.umap(adata)

# Leiden at multiple resolutions
resolutions = [0.2, 0.4, 0.6, 0.8, 1.0]
for res in resolutions:
    key = f"leiden_res_{res}"
    sc.tl.leiden(adata, resolution=res, key_added=key)
    print(key, "->", adata.obs[key].nunique(), "clusters")

# save
out_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_processed_multi_leiden.h5ad"
adata.write_h5ad(out_path)
print("Saved:", out_path)

sc.pl.umap(
    adata,
    color=["leiden_res_0.2", "leiden_res_0.4", "leiden_res_0.6", "leiden_res_0.8", "leiden_res_1.0"],
    wspace=0.4
)

adata.write_h5ad("/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_processed_selected_leiden.h5ad")

"""***2) CELL TYPE LABELLING -- TRIAL 1***"""

adata.obs["leiden"] = adata.obs["leiden_res_0.8"]

adata.write_h5ad("/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_processed_leiden08.h5ad")

sc.tl.rank_genes_groups(adata, groupby="leiden", method="wilcoxon")
sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False)

import scanpy as sc

adata = sc.read_h5ad("/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_processed_leiden08.h5ad")

# CELL TYPE MAP

cell_type_map = {
    "0": "Low-quality / ribosomal",
    "1": "Classical monocytes",
    "2": "CD4 T cells",
    "3": "IFN-stimulated T cells",
    "4": "Cytotoxic T / NK cells",
    "5": "Cytotoxic T cells",
    "6": "NK cells",
    "7": "Low-quality / ribosomal",
    "8": "Erythrocytes",
    "9": "B cells",
    "10": "IFN-stimulated monocytes",
    "11": "CD8 T cells",
    "12": "Classical monocytes",
    "13": "Erythroids",
    "14": "Erythrocytes",
    "15": "Cytotoxic T / NK cells",
    "16": "pDC",
    "17": "cDC",
    "18": "Platelets",
    "19": "Plasma cells"
}

adata.obs["cell_type"] = adata.obs["leiden"].map(cell_type_map)

sc.pl.umap(adata, color="cell_type", legend_loc="on data")

import scanpy as sc
import matplotlib.pyplot as plt
import pandas as pd

adata.obs["leiden_res_0.8"] = adata.obs["leiden_res_0.8"].astype(str)

# UMAP with cluster numbers on the plot
sc.pl.umap(
    adata,
    color="leiden_res_0.8",
    legend_loc="on data",
    legend_fontsize=12,
    legend_fontweight="bold",
    size=3,
    frameon=True,
    title="Leiden clusters"
)

# print number legend as a clean table
legend_df = pd.DataFrame({
    "cluster": list(cell_type_map.keys()),
    "cell_type": list(cell_type_map.values())
}).sort_values("cluster", key=lambda x: x.astype(int))

legend_df

bad_types = [
    "Low-quality / ribosomal",
    "Erythroids",
    "Erythrocytes",
    "Platelets"
]

adata_clean = adata[~adata.obs["cell_type"].isin(bad_types)].copy()

print("Before:", adata.shape)
print("After:", adata_clean.shape)

adata_clean.obs["cell_type"] = adata.obs["leiden"].map(cell_type_map)

sc.pl.umap(adata_clean, color="cell_type", legend_loc="on data")

adata_clean.write_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad"
)

import scanpy as sc
import numpy as np

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad"
)

# subsample ~50k cells
idx = np.random.choice(adata.n_obs, 50000, replace=False)
adata_sub = adata[idx].copy()

print("Subsample:", adata_sub)

# CELL TYPIST

import celltypist

predictions = celltypist.annotate(
    adata_sub,
    model="Immune_All_Low.pkl",
    majority_voting=True
)

adata_sub.obs = adata_sub.obs.join(predictions.predicted_labels)

import pandas as pd

pd.crosstab(
    adata_sub.obs["leiden_res_0.8"],
    adata_sub.obs["majority_voting"],
    normalize="index"
).round(2)

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad"
)

healthy_samples = [
    "GSM4029940_JB19001",
    "GSM4029942_JB19003",
    "GSM4029947_JB19009",
    "GSM4029948_JB19010",
    "GSM4029949_JB19011",
]

sick_samples = [
    "GSM4029950_JB19013",
    "GSM4029951_JB19014",
    "GSM4029952_JB19015",
    "GSM4029943_JB19004",
    "GSM4029944_JB19006",
    "GSM4029945_JB19007",
    "GSM4029946_JB19008",
]

# ----- CHANGE "sample" if needed -----
sample_col = "sample"

# Create condition labels
adata.obs["condition"] = "Unknown"

adata.obs.loc[
    adata.obs[sample_col].isin(healthy_samples),
    "condition"
] = "Healthy"

adata.obs.loc[
    adata.obs[sample_col].isin(sick_samples),
    "condition"
] = "Sick"

# Remove unknown cells if any
adata = adata[adata.obs["condition"] != "Unknown"].copy()

# Compute UMAP if not already present
if "X_umap" not in adata.obsm:
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)

    sc.pp.highly_variable_genes(
        adata,
        n_top_genes=3000
    )

    adata = adata[:, adata.var.highly_variable].copy()

    sc.pp.scale(adata, max_value=10)
    sc.tl.pca(adata)

    sc.pp.neighbors(
        adata,
        n_neighbors=15,
        n_pcs=30
    )

    sc.tl.umap(adata)

# Plot
sc.pl.umap(
    adata,
    color="condition",
    title="Healthy vs Sick UMAP",
    frameon=False,
    size=20
)

"""***2) SANITY CHECKS***"""

import scanpy as sc

adata = sc.read_h5ad("/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad")

# check all metadata columns
print(adata.obs.columns.tolist())

import scanpy as sc
import pandas as pd
import numpy as np
from scipy import sparse

# load your final cleaned adult object
adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad"
)

print(adata)
print(adata.obs.columns.tolist())

# required metadata checks
assert "cell_type" in adata.obs.columns, "Missing cell_type column"
assert "sample" in adata.obs.columns, "Missing sample column"

# make cell_type categorical
adata.obs["cell_type"] = adata.obs["cell_type"].astype("category")

# optional but useful
if "gsm_id" in adata.obs.columns:
    adata.obs["gsm_id"] = adata.obs["gsm_id"].astype(str)

print(adata.obs["cell_type"].value_counts())
print(adata.obs["sample"].value_counts())

# ensure counts layer exists
if "counts" not in adata.layers:
    print("counts layer missing -> creating it from current X")
    adata.layers["counts"] = adata.X.copy()
else:
    print("counts layer already present")

# quick diagnostic
xmax = adata.X.max() if not sparse.issparse(adata.X) else adata.X.max()
xmin = adata.X.min() if not sparse.issparse(adata.X) else adata.X.min()

print("X min:", xmin)
print("X max:", xmax)

# no missing cell labels
print("Missing cell_type:", adata.obs["cell_type"].isna().sum())

# enough cells per group
print(adata.obs["cell_type"].value_counts())

# check for duplicate cell names
print("Duplicated obs_names:", adata.obs_names.duplicated().sum())

"""***3) SPLITTING***"""

import scanpy as sc

adata = sc.read_h5ad(
    "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_final_liana.h5ad"
)

healthy_samples = [
    "GSM4029940_JB19001",
    "GSM4029942_JB19003",
    "GSM4029947_JB19009",
    "GSM4029948_JB19010",
    "GSM4029949_JB19011",
]

sick_samples = [
    "GSM4029950_JB19013",
    "GSM4029951_JB19014",
    "GSM4029952_JB19015",
    "GSM4029943_JB19004",
    "GSM4029944_JB19006",
    "GSM4029945_JB19007",
    "GSM4029946_JB19008",
]

adata.obs["condition"] = "unknown"
adata.obs.loc[adata.obs["sample"].isin(healthy_samples), "condition"] = "healthy"
adata.obs.loc[adata.obs["sample"].isin(sick_samples), "condition"] = "sick"

print(adata.obs["condition"].value_counts())
print(adata.obs[["sample", "condition"]].drop_duplicates().sort_values("sample"))

adata_adult_healthy = adata[adata.obs["condition"] == "healthy"].copy()
adata_adult_sick = adata[adata.obs["condition"] == "sick"].copy()

print("Healthy:", adata_adult_healthy)
print("Sick:", adata_adult_sick)

healthy_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_healthy_liana.h5ad"
sick_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_sick_liana.h5ad"

adata_adult_healthy.write_h5ad(healthy_path)
adata_adult_sick.write_h5ad(sick_path)

print("Saved healthy:", healthy_path)
print("Saved sick:", sick_path)