# -*- coding: utf-8 -*-
"""2C_GSE135779_ADULT_HEALTHY_LIANA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msqoP3G7sztWRW2xIfq_5uxLxOUp25ei
"""

!pip install -q liana scanpy mygene

from google.colab import drive
drive.mount('/content/drive')

import scanpy as sc

adata_path = "/content/drive/MyDrive/GSE135779/adult_individual_h5ad/adata_adult_healthy_liana.h5ad"

adata = sc.read_h5ad(adata_path)

import liana as li

res = li.mt.rank_aggregate(
    adata,
    groupby="cell_type",
    resource_name="consensus",
    expr_prop=0.1,
    use_raw=False,
    verbose=True
)

print("\n--- After LIANA ---")
print("adata_adult.uns keys:", adata.uns.keys())

res = adata.uns["liana_res"].copy()

print("Shape:", res.shape)
print("Columns:", res.columns.tolist())
print("Unique sources:", res["source"].unique())

res.head(10)

import pandas as pd

# load results
df = pd.read_csv("/content/drive/MyDrive/GSE135779/Results/aH_liana/aH_liana_res.csv")

# sort by strength (descending) and take top 100
top100 = df.sort_values("magnitude_rank", ascending=False).head(100)

# save
top100.to_csv("/content/drive/MyDrive/GSE135779/Results/aH_liana/top100_interactions.csv", index=False)

# preview
top100.head()

res = adata.uns["liana_res"].copy()
res["condition"] = "aH"

save_dir = "/content/drive/MyDrive/GSE135779/Results/aH_liana"

csv_path = f"{save_dir}/aH_liana_res.csv"
h5ad_path = f"{save_dir}/aH_with_liana.h5ad"

res.to_csv(csv_path, index=False)
adata.write(h5ad_path)

print("Saved:")
print(csv_path)
print(h5ad_path)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# path to your file
file_path = "/content/drive/MyDrive/GSE135779/Results/aH_liana/aH_liana_res.csv"

# load data
res = pd.read_csv(file_path)

# build heatmap matrix
heatmap = res.groupby(["source", "target"])["lrscore"].mean().unstack().fillna(0)

# plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(heatmap, cmap="Reds")

plt.title("aH Cell–Cell Communication")
plt.xlabel("Target")
plt.ylabel("Source")

# save
save_path = "/content/drive/MyDrive/GSE135779/Results/aH_liana/aH_heatmap.png"
plt.tight_layout()
plt.savefig(save_path, dpi=300)

plt.show()

print("Saved to:", save_path)