# -*- coding: utf-8 -*-
"""3A_GSE135779_aH_aSLE_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VeQ_M7a5z6PQzKfYrZzdl6djihZQZP6V
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# Input folders
asle_dir = "/content/drive/MyDrive/GSE135779/Results/aSLE_liana"
ah_dir   = "/content/drive/MyDrive/GSE135779/Results/aH_liana"

# Output folder
out_dir = "/content/drive/MyDrive/GSE135779/Results/aH_aSLE_comparison"
os.makedirs(out_dir, exist_ok=True)

# Input files
asle_file = os.path.join(asle_dir, "aSLE_liana_res.csv")
ah_file   = os.path.join(ah_dir, "aH_liana_res.csv")

# Load
res_asle = pd.read_csv(asle_file)
res_ah   = pd.read_csv(ah_file)

print("aSLE shape:", res_asle.shape)
print("aH shape:", res_ah.shape)
display(res_asle.head())
display(res_ah.head())

def make_interaction_id(df):
    df = df.copy()
    df["interaction_id"] = (
        df["source"].astype(str) + "|" +
        df["target"].astype(str) + "|" +
        df["ligand_complex"].astype(str) + "|" +
        df["receptor_complex"].astype(str)
    )
    return df

res_asle = make_interaction_id(res_asle)
res_ah   = make_interaction_id(res_ah)

res_asle["condition"] = "aSLE"
res_ah["condition"] = "aH"

keep_cols = [
    "interaction_id",
    "source", "target", "ligand_complex", "receptor_complex",
    "lr_means", "cellphone_pvals", "expr_prod", "scaled_weight",
    "lr_logfc", "spec_weight", "lrscore",
    "specificity_rank", "magnitude_rank",
    "condition"
]

res_asle_sub = res_asle[keep_cols].copy()
res_ah_sub   = res_ah[keep_cols].copy()

# MERGED TABLE
merged = pd.merge(
    res_ah_sub.drop(columns=["condition"]),
    res_asle_sub.drop(columns=["condition"]),
    on="interaction_id",
    how="outer",
    suffixes=("_aH", "_aSLE")
)

# add presence labels
merged["present_in_aH"] = merged["magnitude_rank_aH"].notna()
merged["present_in_aSLE"] = merged["magnitude_rank_aSLE"].notna()

# direction of rank difference for shared interactions
merged["rank_diff_aH_minus_aSLE"] = (
    merged["magnitude_rank_aH"] - merged["magnitude_rank_aSLE"]
)

merged.to_csv(os.path.join(out_dir, "aH_vs_aSLE_liana_merged.csv"), index=False)

print("Saved merged file")
print(merged.shape)
display(merged.head())

# SHARED INTERACTIONS STRONGER IN ASLE

shared = merged[
    merged["present_in_aH"] & merged["present_in_aSLE"]
].copy()

shared["stronger_condition"] = np.where(
    shared["magnitude_rank_aSLE"] < shared["magnitude_rank_aH"],
    "aSLE",
    "aH"
)

shared["rank_difference"] = shared["magnitude_rank_aH"] - shared["magnitude_rank_aSLE"]
shared["abs_rank_difference"] = shared["rank_difference"].abs()

asle_stronger = shared[shared["stronger_condition"] == "aSLE"].copy()
asle_stronger = asle_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_aSLE"],
    ascending=[False, True]
)

asle_stronger.to_csv(
    os.path.join(out_dir, "aSLE_stronger_shared_interactions.csv"),
    index=False
)

asle_stronger.head(50).to_csv(
    os.path.join(out_dir, "aSLE_stronger_top50.csv"),
    index=False
)

print("Saved aSLE stronger shared interactions")
display(asle_stronger.head(10))

# SHARED INTERACTIONS STRONGER IN AH

ah_stronger = shared[shared["stronger_condition"] == "aH"].copy()
ah_stronger = ah_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_aH"],
    ascending=[True, True]
)

ah_stronger.to_csv(
    os.path.join(out_dir, "aH_stronger_shared_interactions.csv"),
    index=False
)

ah_stronger.head(50).to_csv(
    os.path.join(out_dir, "aH_stronger_top50.csv"),
    index=False
)

print("Saved aH stronger shared interactions")
display(ah_stronger.head(10))

# ASLE ONLY INTERACTIONS

asle_only = merged[
    (~merged["present_in_aH"]) & (merged["present_in_aSLE"])
].copy()

asle_only = asle_only.sort_values(by="magnitude_rank_aSLE", ascending=True)

asle_only.to_csv(
    os.path.join(out_dir, "aSLE_only_interactions.csv"),
    index=False
)

print("Saved aSLE-only interactions")
display(asle_only.head(10))

# AH ONLY INTERACTIONS

ah_only = merged[
    (merged["present_in_aH"]) & (~merged["present_in_aSLE"])
].copy()

ah_only = ah_only.sort_values(by="magnitude_rank_aH", ascending=True)

ah_only.to_csv(
    os.path.join(out_dir, "aH_only_interactions.csv"),
    index=False
)

print("Saved aH-only interactions")
display(ah_only.head(10))

# FILE SAVE

summary = pd.DataFrame({
    "metric": [
        "total_interactions_aH",
        "total_interactions_aSLE",
        "shared_interactions",
        "aH_only_interactions",
        "aSLE_only_interactions",
        "shared_stronger_in_aH",
        "shared_stronger_in_aSLE"
    ],
    "value": [
        len(res_ah_sub),
        len(res_asle_sub),
        len(shared),
        len(ah_only),
        len(asle_only),
        len(ah_stronger),
        len(asle_stronger)
    ]
})

summary.to_csv(
    os.path.join(out_dir, "aH_aSLE_comparison_summary.csv"),
    index=False
)

print("Saved summary table")
display(summary)

"""***VISUALIZATION***"""

# BARPLOT
import matplotlib.pyplot as plt
import seaborn as sns

# take top 20 strongest aSLE interactions
top_asle = asle_stronger.head(20).copy()

# create readable label
top_asle["label"] = (
    top_asle["source_aSLE"] + " → " +
    top_asle["target_aSLE"] + " | " +
    top_asle["ligand_complex_aSLE"] + "-" +
    top_asle["receptor_complex_aSLE"]
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=top_asle,
    y="label",
    x="rank_difference"
)

plt.title("Top aSLE-Enriched Cell-Cell Interactions")
plt.xlabel("Rank Difference (aH - aSLE)")
plt.ylabel("Interaction")

plt.tight_layout()
plt.show()

# HEATMAP: aSLE vs aH
# Positive/red = stronger in aSLE
# Negative/blue = stronger in aH

heatmap_data = shared.copy()

heatmap_data["rank_difference"] = (
    heatmap_data["magnitude_rank_aH"] -
    heatmap_data["magnitude_rank_aSLE"]
)

heatmap_matrix = (
    heatmap_data
    .groupby(["source_aSLE", "target_aSLE"])["rank_difference"]
    .mean()
    .unstack()
    .fillna(0)
)

plt.figure(figsize=(11, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": "Mean rank difference\n(+ aSLE stronger, - aH stronger)"
    }
)

plt.title("Differential Cell–Cell Communication: aSLE vs aH")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# NET WORK PLOT

import networkx as nx

# use top interactions only (keeps graph readable)
net_df = asle_stronger.head(30)

G = nx.DiGraph()

for _, row in net_df.iterrows():
    G.add_edge(
        row["source_aSLE"],
        row["target_aSLE"],
        weight=row["rank_difference"]
    )

plt.figure(figsize=(10, 10))

pos = nx.spring_layout(G, seed=42)

edges = G.edges(data=True)
weights = [d["weight"] for (_, _, d) in edges]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=10,
    width=[w * 2 for w in weights]
)

plt.title("Top aSLE Cell–Cell Communication Network")
plt.show()

# BOTH DIRECTIONS IN ONE PLOT

top_ah = ah_stronger.head(20).copy()
top_ah["direction"] = "aH stronger"

top_asle = asle_stronger.head(20).copy()
top_asle["direction"] = "aSLE stronger"

combined = pd.concat([top_asle, top_ah])

combined["label"] = (
    combined["source_aSLE"].fillna(combined["source_aH"]) + " → " +
    combined["target_aSLE"].fillna(combined["target_aH"])
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=combined,
    y="label",
    x="abs_rank_difference",
    hue="direction"
)

plt.title("Differential Cell Communication (aSLE vs aH)")
plt.xlabel("Absolute Rank Difference")

plt.tight_layout()
plt.show()

