# -*- coding: utf-8 -*-
"""3B_GSE135779_cH_cSLE_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v75yijm1OSM64CZZtLtTPpIS_qTJvSRk
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# Input folders
csle_dir = "/content/drive/MyDrive/GSE135779/Results/cSLE_liana"
ch_dir   = "/content/drive/MyDrive/GSE135779/Results/cH_liana"

# Output folder
out_dir = "/content/drive/MyDrive/GSE135779/Results/cH_cSLE_comparison"
os.makedirs(out_dir, exist_ok=True)

# Input files
csle_file = os.path.join(csle_dir, "cSLE_liana_res.csv")
ch_file   = os.path.join(ch_dir, "cH_liana_res.csv")

# Load
res_csle = pd.read_csv(csle_file)
res_ch   = pd.read_csv(ch_file)

print("cSLE shape:", res_csle.shape)
print("cH shape:", res_ch.shape)
display(res_csle.head())
display(res_ch.head())

def make_interaction_id(df):
    df = df.copy()
    df["interaction_id"] = (
        df["source"].astype(str) + "|" +
        df["target"].astype(str) + "|" +
        df["ligand_complex"].astype(str) + "|" +
        df["receptor_complex"].astype(str)
    )
    return df

res_csle = make_interaction_id(res_csle)
res_ch   = make_interaction_id(res_ch)

res_csle["condition"] = "cSLE"
res_ch["condition"] = "cH"

keep_cols = [
    "interaction_id",
    "source", "target", "ligand_complex", "receptor_complex",
    "lr_means", "cellphone_pvals", "expr_prod", "scaled_weight",
    "lr_logfc", "spec_weight", "lrscore",
    "specificity_rank", "magnitude_rank",
    "condition"
]

res_csle_sub = res_csle[keep_cols].copy()
res_ch_sub   = res_ch[keep_cols].copy()

# MERGED TABLE
merged = pd.merge(
    res_ch_sub.drop(columns=["condition"]),
    res_csle_sub.drop(columns=["condition"]),
    on="interaction_id",
    how="outer",
    suffixes=("_cH", "_cSLE")
)

# add presence labels
merged["present_in_cH"] = merged["magnitude_rank_cH"].notna()
merged["present_in_cSLE"] = merged["magnitude_rank_cSLE"].notna()

# direction of rank difference for shared interactions
# Because lower LIANA magnitude_rank = stronger:
# positive = stronger in cSLE
# negative = stronger in cH
merged["rank_diff_cH_minus_cSLE"] = (
    merged["magnitude_rank_cH"] - merged["magnitude_rank_cSLE"]
)

merged.to_csv(os.path.join(out_dir, "cH_vs_cSLE_liana_merged.csv"), index=False)

print("Saved merged file")
print(merged.shape)
display(merged.head())

# SHARED INTERACTIONS STRONGER IN cSLE

shared = merged[
    merged["present_in_cH"] & merged["present_in_cSLE"]
].copy()

shared["stronger_condition"] = np.where(
    shared["magnitude_rank_cSLE"] < shared["magnitude_rank_cH"],
    "cSLE",
    "cH"
)

shared["rank_difference"] = shared["magnitude_rank_cH"] - shared["magnitude_rank_cSLE"]
shared["abs_rank_difference"] = shared["rank_difference"].abs()

csle_stronger = shared[shared["stronger_condition"] == "cSLE"].copy()
csle_stronger = csle_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_cSLE"],
    ascending=[False, True]
)

csle_stronger.to_csv(
    os.path.join(out_dir, "cSLE_stronger_shared_interactions.csv"),
    index=False
)

csle_stronger.head(50).to_csv(
    os.path.join(out_dir, "cSLE_stronger_top50.csv"),
    index=False
)

print("Saved cSLE stronger shared interactions")
display(csle_stronger.head(10))

# SHARED INTERACTIONS STRONGER IN cH

ch_stronger = shared[shared["stronger_condition"] == "cH"].copy()
ch_stronger = ch_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_cH"],
    ascending=[True, True]
)

ch_stronger.to_csv(
    os.path.join(out_dir, "cH_stronger_shared_interactions.csv"),
    index=False
)

ch_stronger.head(50).to_csv(
    os.path.join(out_dir, "cH_stronger_top50.csv"),
    index=False
)

print("Saved cH stronger shared interactions")
display(ch_stronger.head(10))

# cSLE ONLY INTERACTIONS

csle_only = merged[
    (~merged["present_in_cH"]) & (merged["present_in_cSLE"])
].copy()

csle_only = csle_only.sort_values(by="magnitude_rank_cSLE", ascending=True)

csle_only.to_csv(
    os.path.join(out_dir, "cSLE_only_interactions.csv"),
    index=False
)

print("Saved cSLE-only interactions")
display(csle_only.head(10))

# cH ONLY INTERACTIONS

ch_only = merged[
    (merged["present_in_cH"]) & (~merged["present_in_cSLE"])
].copy()

ch_only = ch_only.sort_values(by="magnitude_rank_cH", ascending=True)

ch_only.to_csv(
    os.path.join(out_dir, "cH_only_interactions.csv"),
    index=False
)

print("Saved cH-only interactions")
display(ch_only.head(10))

# FILE SAVE

summary = pd.DataFrame({
    "metric": [
        "total_interactions_cH",
        "total_interactions_cSLE",
        "shared_interactions",
        "cH_only_interactions",
        "cSLE_only_interactions",
        "shared_stronger_in_cH",
        "shared_stronger_in_cSLE"
    ],
    "value": [
        len(res_ch_sub),
        len(res_csle_sub),
        len(shared),
        len(ch_only),
        len(csle_only),
        len(ch_stronger),
        len(csle_stronger)
    ]
})

summary.to_csv(
    os.path.join(out_dir, "cH_cSLE_comparison_summary.csv"),
    index=False
)

print("Saved summary table")
display(summary)

"""***VISUALIZATION***"""

# BARPLOT
import matplotlib.pyplot as plt
import seaborn as sns

# take top 20 strongest cSLE interactions
top_csle = csle_stronger.head(20).copy()

# create readable label
top_csle["label"] = (
    top_csle["source_cSLE"] + " → " +
    top_csle["target_cSLE"] + " | " +
    top_csle["ligand_complex_cSLE"] + "-" +
    top_csle["receptor_complex_cSLE"]
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=top_csle,
    y="label",
    x="rank_difference"
)

plt.title("Top cSLE-Enriched Cell-Cell Interactions")
plt.xlabel("Rank Difference (cH - cSLE)")
plt.ylabel("Interaction")

plt.tight_layout()
plt.show()

# HEATMAP: cSLE vs cH
# Positive/red = stronger in cSLE
# Negative/blue = stronger in cH

heatmap_data = shared.copy()

heatmap_data["rank_difference"] = (
    heatmap_data["magnitude_rank_cH"] -
    heatmap_data["magnitude_rank_cSLE"]
)

heatmap_matrix = (
    heatmap_data
    .groupby(["source_cSLE", "target_cSLE"])["rank_difference"]
    .mean()
    .unstack()
    .fillna(0)
)

plt.figure(figsize=(11, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": "Mean rank difference\n(+ cSLE stronger, - cH stronger)"
    }
)

plt.title("Differential Cell–Cell Communication: cSLE vs cH")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# NETWORK PLOT

import networkx as nx

# use top interactions only
net_df = csle_stronger.head(30)

G = nx.DiGraph()

for _, row in net_df.iterrows():
    G.add_edge(
        row["source_cSLE"],
        row["target_cSLE"],
        weight=row["rank_difference"]
    )

plt.figure(figsize=(10, 10))

pos = nx.spring_layout(G, seed=42)

edges = G.edges(data=True)
weights = [d["weight"] for (_, _, d) in edges]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=10,
    width=[w * 2 for w in weights]
)

plt.title("Top cSLE Cell–Cell Communication Network")
plt.show()

# BOTH DIRECTIONS IN ONE PLOT

top_ch = ch_stronger.head(20).copy()
top_ch["direction"] = "cH stronger"

top_csle = csle_stronger.head(20).copy()
top_csle["direction"] = "cSLE stronger"

combined = pd.concat([top_csle, top_ch])

combined["label"] = (
    combined["source_cSLE"].fillna(combined["source_cH"]) + " → " +
    combined["target_cSLE"].fillna(combined["target_cH"])
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=combined,
    y="label",
    x="abs_rank_difference",
    hue="direction"
)

plt.title("Differential Cell Communication (cSLE vs cH)")
plt.xlabel("Absolute Rank Difference")

plt.tight_layout()
plt.show()





