# -*- coding: utf-8 -*-
"""3C_GSE135779_cH_aH_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itRtDWYHWfuLXA2Q3biqoq9thBNv_OfP
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

# Input folders
ah_dir = "/content/drive/MyDrive/GSE135779/Results/aH_liana"
ch_dir = "/content/drive/MyDrive/GSE135779/Results/cH_liana"

# Output folder
out_dir = "/content/drive/MyDrive/GSE135779/Results/cH_aH_comparison"
os.makedirs(out_dir, exist_ok=True)

# Input files
ah_file = os.path.join(ah_dir, "aH_liana_res.csv")
ch_file = os.path.join(ch_dir, "cH_liana_res.csv")

# Load
res_ah = pd.read_csv(ah_file)
res_ch = pd.read_csv(ch_file)

print("aH shape:", res_ah.shape)
print("cH shape:", res_ch.shape)
display(res_ah.head())
display(res_ch.head())

def make_interaction_id(df):
    df = df.copy()
    df["interaction_id"] = (
        df["source"].astype(str) + "|" +
        df["target"].astype(str) + "|" +
        df["ligand_complex"].astype(str) + "|" +
        df["receptor_complex"].astype(str)
    )
    return df

res_ah = make_interaction_id(res_ah)
res_ch = make_interaction_id(res_ch)

res_ah["condition"] = "aH"
res_ch["condition"] = "cH"

keep_cols = [
    "interaction_id",
    "source", "target", "ligand_complex", "receptor_complex",
    "lr_means", "cellphone_pvals", "expr_prod", "scaled_weight",
    "lr_logfc", "spec_weight", "lrscore",
    "specificity_rank", "magnitude_rank",
    "condition"
]

res_ah_sub = res_ah[keep_cols].copy()
res_ch_sub = res_ch[keep_cols].copy()

# MERGED TABLE
merged = pd.merge(
    res_ch_sub.drop(columns=["condition"]),
    res_ah_sub.drop(columns=["condition"]),
    on="interaction_id",
    how="outer",
    suffixes=("_ch", "_ah")
)

# add presence labels
merged["present_in_ch"] = merged["magnitude_rank_ch"].notna()
merged["present_in_ah"] = merged["magnitude_rank_ah"].notna()

# direction of rank difference for shared interactions
merged["rank_diff_ch_minus_ah"] = (
    merged["magnitude_rank_ch"] - merged["magnitude_rank_ah"]
)

merged.to_csv(os.path.join(out_dir, "ch_vs_ah_liana_merged.csv"), index=False)

print("Saved merged file")
print(merged.shape)
display(merged.head())

# SHARED INTERACTIONS STRONGER IN aH

shared = merged[
    merged["present_in_ch"] & merged["present_in_ah"]
].copy()

shared["stronger_condition"] = np.where(
    shared["magnitude_rank_ah"] < shared["magnitude_rank_ch"],
    "ah",
    "ch"
)

shared["rank_difference"] = shared["magnitude_rank_ch"] - shared["magnitude_rank_ah"]
shared["abs_rank_difference"] = shared["rank_difference"].abs()

ah_stronger = shared[shared["stronger_condition"] == "ah"].copy()
ah_stronger = ah_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_ah"],
    ascending=[False, True]
)

ah_stronger.to_csv(
    os.path.join(out_dir, "ah_stronger_shared_interactions.csv"),
    index=False
)

ah_stronger.head(50).to_csv(
    os.path.join(out_dir, "ah_stronger_top50.csv"),
    index=False
)

print("Saved aH stronger shared interactions")
display(ah_stronger.head(10))

# SHARED INTERACTIONS STRONGER IN CH

ch_stronger = shared[shared["stronger_condition"] == "ch"].copy()
ch_stronger = ch_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_ch"],
    ascending=[True, True]
)

ch_stronger.to_csv(
    os.path.join(out_dir, "ch_stronger_shared_interactions.csv"),
    index=False
)

ch_stronger.head(50).to_csv(
    os.path.join(out_dir, "ch_stronger_top50.csv"),
    index=False
)

print("Saved ch stronger shared interactions")
display(ch_stronger.head(10))

# aH ONLY INTERACTIONS

ah_only = merged[
    (~merged["present_in_ch"]) & (merged["present_in_ah"])
].copy()

ah_only = ah_only.sort_values(by="magnitude_rank_ah", ascending=True)

ah_only.to_csv(
    os.path.join(out_dir, "ah_only_interactions.csv"),
    index=False
)

print("Saved aH-only interactions")
display(ah_only.head(10))

# CH ONLY INTERACTIONS

ch_only = merged[
    (merged["present_in_ch"]) & (~merged["present_in_ah"])
].copy()

ch_only = ch_only.sort_values(by="magnitude_rank_ch", ascending=True)

ch_only.to_csv(
    os.path.join(out_dir, "ch_only_interactions.csv"),
    index=False
)

print("Saved ch-only interactions")
display(ch_only.head(10))

"""***VISUALIZATION***"""

# BARPLOT
import matplotlib.pyplot as plt
import seaborn as sns

# take top 20 strongest aH interactions
top_ah = ah_stronger.head(20).copy()

# create readable label
top_ah["label"] = (
    top_ah["source_ah"] + " → " +
    top_ah["target_ah"] + " | " +
    top_ah["ligand_complex_ah"] + "-" +
    top_ah["receptor_complex_ah"]
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=top_ah,
    y="label",
    x="rank_difference"
)

plt.title("Top aH-Enriched Cell-Cell Interactions")
plt.xlabel("Rank Difference (cH - aH)")
plt.ylabel("Interaction")

plt.tight_layout()
plt.show()

# HEATMAP

import matplotlib.pyplot as plt
import seaborn as sns

# Positive/red = stronger in aH
# Negative/blue = stronger in cH

heatmap_data = shared.copy()

heatmap_matrix = (
    heatmap_data
    .groupby(["source_ah", "target_ah"])["rank_difference"]
    .mean()
    .unstack()
    .fillna(0)
)

plt.figure(figsize=(10, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": "Mean rank difference\n(+ aH stronger, - cH stronger)"
    }
)

plt.title("Differential Cell–Cell Communication: aH vs cH")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# NETWORK PLOT

import networkx as nx

# use top interactions only (keeps graph readable)
net_df = ah_stronger.head(30)

G = nx.DiGraph()

for _, row in net_df.iterrows():
    G.add_edge(
        row["source_ah"],
        row["target_ah"],
        weight=row["rank_difference"]
    )

plt.figure(figsize=(10, 10))

pos = nx.spring_layout(G, seed=42)

edges = G.edges(data=True)
weights = [d["weight"] for (_, _, d) in edges]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=10,
    width=[w * 2 for w in weights]
)

plt.title("Top aH Cell–Cell Communication Network")
plt.show()

# BOTH DIRECTIONS IN ONE PLOT

top_ch = ch_stronger.head(20).copy()
top_ch["direction"] = "cH stronger"

top_ah = ah_stronger.head(20).copy()
top_ah["direction"] = "aH stronger"

combined = pd.concat([top_ah, top_ch])

# create label safely using available columns
combined["source"] = combined["source_ah"].fillna(combined["source_ch"])
combined["target"] = combined["target_ah"].fillna(combined["target_ch"])

combined["label"] = combined["source"] + " → " + combined["target"]

plt.figure(figsize=(10, 8))

sns.barplot(
    data=combined,
    y="label",
    x="abs_rank_difference",
    hue="direction"
)

plt.title("Differential Cell Communication (aH vs cH)")
plt.xlabel("Absolute Rank Difference")

plt.tight_layout()
plt.show()