# -*- coding: utf-8 -*-
"""3E_GSE135779_aH_cSLE_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_u-QHOQNprW5hzb7BtQGt20B85KmpBZ0
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

# Input folders
csle_dir = "/content/drive/MyDrive/GSE135779/Results/cSLE_liana"
ah_dir   = "/content/drive/MyDrive/GSE135779/Results/aH_liana"

# Output folder
out_dir = "/content/drive/MyDrive/GSE135779/Results/aH_cSLE_comparison"
os.makedirs(out_dir, exist_ok=True)

# Input files
csle_file = os.path.join(csle_dir, "cSLE_liana_res.csv")
ah_file   = os.path.join(ah_dir, "aH_liana_res.csv")

# Load
res_csle = pd.read_csv(csle_file)
res_ah   = pd.read_csv(ah_file)

print("cSLE shape:", res_csle.shape)
print("aH shape:", res_ah.shape)
display(res_csle.head())
display(res_ah.head())

def make_interaction_id(df):
    df = df.copy()
    df["interaction_id"] = (
        df["source"].astype(str) + "|" +
        df["target"].astype(str) + "|" +
        df["ligand_complex"].astype(str) + "|" +
        df["receptor_complex"].astype(str)
    )
    return df

res_csle = make_interaction_id(res_csle)
res_ah   = make_interaction_id(res_ah)

res_csle["condition"] = "cSLE"
res_ah["condition"] = "aH"

keep_cols = [
    "interaction_id",
    "source", "target", "ligand_complex", "receptor_complex",
    "lr_means", "cellphone_pvals", "expr_prod", "scaled_weight",
    "lr_logfc", "spec_weight", "lrscore",
    "specificity_rank", "magnitude_rank",
    "condition"
]

res_csle_sub = res_csle[keep_cols].copy()
res_ah_sub   = res_ah[keep_cols].copy()

# MERGED TABLE
merged = pd.merge(
    res_ah_sub.drop(columns=["condition"]),
    res_csle_sub.drop(columns=["condition"]),
    on="interaction_id",
    how="outer",
    suffixes=("_aH", "_cSLE")
)

merged["present_in_aH"] = merged["magnitude_rank_aH"].notna()
merged["present_in_cSLE"] = merged["magnitude_rank_cSLE"].notna()

# Positive/red = stronger in cSLE
# Negative/blue = stronger in aH
merged["rank_diff_aH_minus_cSLE"] = (
    merged["magnitude_rank_aH"] - merged["magnitude_rank_cSLE"]
)

merged.to_csv(os.path.join(out_dir, "aH_vs_cSLE_liana_merged.csv"), index=False)

print("Saved merged file")
print(merged.shape)
display(merged.head())

# SHARED INTERACTIONS STRONGER IN cSLE

shared = merged[
    merged["present_in_aH"] & merged["present_in_cSLE"]
].copy()

shared["stronger_condition"] = np.where(
    shared["magnitude_rank_cSLE"] < shared["magnitude_rank_aH"],
    "cSLE",
    "aH"
)

shared["rank_difference"] = shared["magnitude_rank_aH"] - shared["magnitude_rank_cSLE"]
shared["abs_rank_difference"] = shared["rank_difference"].abs()

csle_stronger = shared[shared["stronger_condition"] == "cSLE"].copy()
csle_stronger = csle_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_cSLE"],
    ascending=[False, True]
)

csle_stronger.to_csv(
    os.path.join(out_dir, "cSLE_stronger_shared_interactions.csv"),
    index=False
)

csle_stronger.head(50).to_csv(
    os.path.join(out_dir, "cSLE_stronger_top50.csv"),
    index=False
)

print("Saved cSLE stronger shared interactions")
display(csle_stronger.head(10))

# SHARED INTERACTIONS STRONGER IN aH

ah_stronger = shared[shared["stronger_condition"] == "aH"].copy()
ah_stronger = ah_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_aH"],
    ascending=[True, True]
)

ah_stronger.to_csv(
    os.path.join(out_dir, "aH_stronger_shared_interactions.csv"),
    index=False
)

ah_stronger.head(50).to_csv(
    os.path.join(out_dir, "aH_stronger_top50.csv"),
    index=False
)

print("Saved aH stronger shared interactions")
display(ah_stronger.head(10))

# cSLE ONLY INTERACTIONS

csle_only = merged[
    (~merged["present_in_aH"]) & (merged["present_in_cSLE"])
].copy()

csle_only = csle_only.sort_values(by="magnitude_rank_cSLE", ascending=True)

csle_only.to_csv(
    os.path.join(out_dir, "cSLE_only_interactions.csv"),
    index=False
)

print("Saved cSLE-only interactions")
display(csle_only.head(10))

# aH ONLY INTERACTIONS

ah_only = merged[
    (merged["present_in_aH"]) & (~merged["present_in_cSLE"])
].copy()

ah_only = ah_only.sort_values(by="magnitude_rank_aH", ascending=True)

ah_only.to_csv(
    os.path.join(out_dir, "aH_only_interactions.csv"),
    index=False
)

print("Saved aH-only interactions")
display(ah_only.head(10))

# SUMMARY TABLE

summary = pd.DataFrame({
    "metric": [
        "total_interactions_aH",
        "total_interactions_cSLE",
        "shared_interactions",
        "aH_only_interactions",
        "cSLE_only_interactions",
        "shared_stronger_in_aH",
        "shared_stronger_in_cSLE"
    ],
    "value": [
        len(res_ah_sub),
        len(res_csle_sub),
        len(shared),
        len(ah_only),
        len(csle_only),
        len(ah_stronger),
        len(csle_stronger)
    ]
})

summary.to_csv(
    os.path.join(out_dir, "aH_cSLE_comparison_summary.csv"),
    index=False
)

print("Saved summary table")
display(summary)

"""***VISUALIZATION***"""

# BARPLOT
import matplotlib.pyplot as plt
import seaborn as sns

top_csle = csle_stronger.head(20).copy()

top_csle["label"] = (
    top_csle["source_cSLE"] + " → " +
    top_csle["target_cSLE"] + " | " +
    top_csle["ligand_complex_cSLE"] + "-" +
    top_csle["receptor_complex_cSLE"]
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=top_csle,
    y="label",
    x="rank_difference"
)

plt.title("Top cSLE-Enriched Cell-Cell Interactions")
plt.xlabel("Rank Difference (aH - cSLE)")
plt.ylabel("Interaction")

plt.tight_layout()
plt.show()

# HEATMAP: cSLE vs aH
# Positive/red = stronger in cSLE
# Negative/blue = stronger in aH

heatmap_data = shared.copy()

heatmap_data["rank_difference"] = (
    heatmap_data["magnitude_rank_aH"] -
    heatmap_data["magnitude_rank_cSLE"]
)

heatmap_matrix = (
    heatmap_data
    .groupby(["source_cSLE", "target_cSLE"])["rank_difference"]
    .mean()
    .unstack()
    .fillna(0)
)

plt.figure(figsize=(11, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": "Mean rank difference\n(+ cSLE stronger, - aH stronger)"
    }
)

plt.title("Differential Cell–Cell Communication: cSLE vs aH")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# NETWORK PLOT

import networkx as nx

net_df = csle_stronger.head(30)

G = nx.DiGraph()

for _, row in net_df.iterrows():
    G.add_edge(
        row["source_cSLE"],
        row["target_cSLE"],
        weight=row["rank_difference"]
    )

plt.figure(figsize=(10, 10))

pos = nx.spring_layout(G, seed=42)

edges = G.edges(data=True)
weights = [d["weight"] for (_, _, d) in edges]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=10,
    width=[w * 2 for w in weights]
)

plt.title("Top cSLE Cell–Cell Communication Network")
plt.show()

# BOTH DIRECTIONS IN ONE PLOT

top_ah = ah_stronger.head(20).copy()
top_ah["direction"] = "aH stronger"

top_csle = csle_stronger.head(20).copy()
top_csle["direction"] = "cSLE stronger"

combined = pd.concat([top_csle, top_ah])

combined["label"] = (
    combined["source_cSLE"].fillna(combined["source_aH"]) + " → " +
    combined["target_cSLE"].fillna(combined["target_aH"])
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=combined,
    y="label",
    x="abs_rank_difference",
    hue="direction"
)

plt.title("Differential Cell Communication (cSLE vs aH)")
plt.xlabel("Absolute Rank Difference")

plt.tight_layout()
plt.show()

import os
import pandas as pd

RESULTS_DIR = '/content/drive/MyDrive/GSE135779/Results'
fpath = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'aH_vs_cSLE_liana_merged.csv')
df = pd.read_csv(fpath)

# Filter to shared only, then rank by mean lrscore
df_shared = df[df['present_in_aH'] & df['present_in_cSLE']].copy()
df_shared['_ranking_score'] = df_shared[['lrscore_aH', 'lrscore_cSLE']].mean(axis=1)
top30 = df_shared.sort_values('_ranking_score', ascending=False).head(30).drop(columns=['_ranking_score'])

out_path = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'top30_aH_vs_cSLE_shared.csv')
top30.to_csv(out_path, index=False)
print(f"Saved {len(top30)} rows")
print(top30[['interaction_id', 'lrscore_aH', 'lrscore_cSLE', 'rank_diff_aH_minus_cSLE']].head(10).to_string())

import os
import pandas as pd

RESULTS_DIR = '/content/drive/MyDrive/GSE135779/Results'
fpath = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'aH_vs_cSLE_liana_merged.csv')
df = pd.read_csv(fpath)

print("Total rows:", len(df))
print("Shared:", (df['present_in_aH'] & df['present_in_cSLE']).sum())
print("aH only:", (df['present_in_aH'] & ~df['present_in_cSLE']).sum())

# Filter to shared only, rank by mean lrscore
df_shared = df[df['present_in_aH'] & df['present_in_cSLE']].copy()
df_shared['_ranking_score'] = df_shared[['lrscore_aH', 'lrscore_cSLE']].mean(axis=1)
top30 = df_shared.sort_values('_ranking_score', ascending=False).head(30).drop(columns=['_ranking_score'])

out_path = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'top30_aH_vs_cSLE_shared.csv')
top30.to_csv(out_path, index=False)
print(f"\nSaved {len(top30)} rows")
print(top30[['interaction_id', 'lrscore_aH', 'lrscore_cSLE', 'rank_diff_aH_minus_cSLE']].head(5).to_string())

import os
import shutil
import pandas as pd

RESULTS_DIR = '/content/drive/MyDrive/GSE135779/Results'
TOP30_DIR = '/content/drive/MyDrive/TOP30_LIANA_RESULTS'

fpath = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'aH_vs_cSLE_liana_merged.csv')
df = pd.read_csv(fpath)

print("Total rows:", len(df))
print("Shared:", (df['present_in_aH'] & df['present_in_cSLE']).sum())

# Filter to shared only, rank by mean lrscore
df_shared = df[df['present_in_aH'] & df['present_in_cSLE']].copy()
df_shared['_ranking_score'] = df_shared[['lrscore_aH', 'lrscore_cSLE']].mean(axis=1)
top30 = df_shared.sort_values('_ranking_score', ascending=False).head(30).drop(columns=['_ranking_score'])

# Save to Results folder
results_path = os.path.join(RESULTS_DIR, 'aH_cSLE_comparison', 'top30_aH_vs_cSLE_shared.csv')
top30.to_csv(results_path, index=False)
print(f"Saved to Results: {results_path}")

# Also overwrite in TOP30_LIANA_RESULTS folder
top30_path = os.path.join(TOP30_DIR, 'top30_aH_vs_cSLE.csv')
top30.to_csv(top30_path, index=False)
print(f"Saved to TOP30_LIANA_RESULTS: {top30_path}")

print(f"\nTop 5 preview:")
print(top30[['interaction_id', 'lrscore_aH', 'lrscore_cSLE', 'rank_diff_aH_minus_cSLE']].head(5).to_string())