# -*- coding: utf-8 -*-
"""3F_GSE135779_cSLE_aSLE_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wq2FClMaC7f2ojy8SY6Infgh7FKyEH8f
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# Input folders
asle_dir = "/content/drive/MyDrive/GSE135779/Results/aSLE_liana"
csle_dir = "/content/drive/MyDrive/GSE135779/Results/cSLE_liana"

# Output folder
out_dir = "/content/drive/MyDrive/GSE135779/Results/cSLE_aSLE_comparison"
os.makedirs(out_dir, exist_ok=True)

# Input files
asle_file = os.path.join(asle_dir, "aSLE_liana_res.csv")
csle_file = os.path.join(csle_dir, "cSLE_liana_res.csv")

# Load
res_asle = pd.read_csv(asle_file)
res_csle = pd.read_csv(csle_file)

print("aSLE shape:", res_asle.shape)
print("cSLE shape:", res_csle.shape)
display(res_asle.head())
display(res_csle.head())

def make_interaction_id(df):
    df = df.copy()
    df["interaction_id"] = (
        df["source"].astype(str) + "|" +
        df["target"].astype(str) + "|" +
        df["ligand_complex"].astype(str) + "|" +
        df["receptor_complex"].astype(str)
    )
    return df

res_asle = make_interaction_id(res_asle)
res_csle = make_interaction_id(res_csle)

res_asle["condition"] = "aSLE"
res_csle["condition"] = "cSLE"

keep_cols = [
    "interaction_id",
    "source", "target", "ligand_complex", "receptor_complex",
    "lr_means", "cellphone_pvals", "expr_prod", "scaled_weight",
    "lr_logfc", "spec_weight", "lrscore",
    "specificity_rank", "magnitude_rank",
    "condition"
]

res_asle_sub = res_asle[keep_cols].copy()
res_csle_sub = res_csle[keep_cols].copy()

# MERGED TABLE
merged = pd.merge(
    res_csle_sub.drop(columns=["condition"]),
    res_asle_sub.drop(columns=["condition"]),
    on="interaction_id",
    how="outer",
    suffixes=("_cSLE", "_aSLE")
)

merged["present_in_cSLE"] = merged["magnitude_rank_cSLE"].notna()
merged["present_in_aSLE"] = merged["magnitude_rank_aSLE"].notna()

# Positive = stronger in aSLE
# Negative = stronger in cSLE
merged["rank_diff_cSLE_minus_aSLE"] = (
    merged["magnitude_rank_cSLE"] - merged["magnitude_rank_aSLE"]
)

merged.to_csv(os.path.join(out_dir, "cSLE_vs_aSLE_liana_merged.csv"), index=False)

print("Saved merged file")
print(merged.shape)
display(merged.head())

# SHARED INTERACTIONS STRONGER IN aSLE

shared = merged[
    merged["present_in_cSLE"] & merged["present_in_aSLE"]
].copy()

shared["stronger_condition"] = np.where(
    shared["magnitude_rank_aSLE"] < shared["magnitude_rank_cSLE"],
    "aSLE",
    "cSLE"
)

shared["rank_difference"] = shared["magnitude_rank_cSLE"] - shared["magnitude_rank_aSLE"]
shared["abs_rank_difference"] = shared["rank_difference"].abs()

asle_stronger = shared[shared["stronger_condition"] == "aSLE"].copy()
asle_stronger = asle_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_aSLE"],
    ascending=[False, True]
)

asle_stronger.to_csv(
    os.path.join(out_dir, "aSLE_stronger_shared_interactions.csv"),
    index=False
)

asle_stronger.head(50).to_csv(
    os.path.join(out_dir, "aSLE_stronger_top50.csv"),
    index=False
)

print("Saved aSLE stronger shared interactions")
display(asle_stronger.head(10))

# SHARED INTERACTIONS STRONGER IN cSLE

csle_stronger = shared[shared["stronger_condition"] == "cSLE"].copy()
csle_stronger = csle_stronger.sort_values(
    by=["rank_difference", "magnitude_rank_cSLE"],
    ascending=[True, True]
)

csle_stronger.to_csv(
    os.path.join(out_dir, "cSLE_stronger_shared_interactions.csv"),
    index=False
)

csle_stronger.head(50).to_csv(
    os.path.join(out_dir, "cSLE_stronger_top50.csv"),
    index=False
)

print("Saved cSLE stronger shared interactions")
display(csle_stronger.head(10))

# aSLE ONLY INTERACTIONS

asle_only = merged[
    (~merged["present_in_cSLE"]) & (merged["present_in_aSLE"])
].copy()

asle_only = asle_only.sort_values(by="magnitude_rank_aSLE", ascending=True)

asle_only.to_csv(
    os.path.join(out_dir, "aSLE_only_interactions.csv"),
    index=False
)

print("Saved aSLE-only interactions")
display(asle_only.head(10))

# cSLE ONLY INTERACTIONS

csle_only = merged[
    (merged["present_in_cSLE"]) & (~merged["present_in_aSLE"])
].copy()

csle_only = csle_only.sort_values(by="magnitude_rank_cSLE", ascending=True)

csle_only.to_csv(
    os.path.join(out_dir, "cSLE_only_interactions.csv"),
    index=False
)

print("Saved cSLE-only interactions")
display(csle_only.head(10))

# SUMMARY TABLE

summary = pd.DataFrame({
    "metric": [
        "total_interactions_cSLE",
        "total_interactions_aSLE",
        "shared_interactions",
        "cSLE_only_interactions",
        "aSLE_only_interactions",
        "shared_stronger_in_cSLE",
        "shared_stronger_in_aSLE"
    ],
    "value": [
        len(res_csle_sub),
        len(res_asle_sub),
        len(shared),
        len(csle_only),
        len(asle_only),
        len(csle_stronger),
        len(asle_stronger)
    ]
})

summary.to_csv(
    os.path.join(out_dir, "cSLE_aSLE_comparison_summary.csv"),
    index=False
)

print("Saved summary table")
display(summary)

# BARPLOT
import matplotlib.pyplot as plt
import seaborn as sns

top_asle = asle_stronger.head(20).copy()

top_asle["label"] = (
    top_asle["source_aSLE"] + " → " +
    top_asle["target_aSLE"] + " | " +
    top_asle["ligand_complex_aSLE"] + "-" +
    top_asle["receptor_complex_aSLE"]
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=top_asle,
    y="label",
    x="rank_difference"
)

plt.title("Top aSLE-Enriched Cell-Cell Interactions")
plt.xlabel("Rank Difference (cSLE - aSLE)")
plt.ylabel("Interaction")

plt.tight_layout()
plt.show()

# HEATMAP: aSLE vs cSLE
# Positive/red = stronger in aSLE
# Negative/blue = stronger in cSLE

heatmap_data = shared.copy()

heatmap_data["rank_difference"] = (
    heatmap_data["magnitude_rank_cSLE"] -
    heatmap_data["magnitude_rank_aSLE"]
)

heatmap_matrix = (
    heatmap_data
    .groupby(["source_aSLE", "target_aSLE"])["rank_difference"]
    .mean()
    .unstack()
    .fillna(0)
)

plt.figure(figsize=(11, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": "Mean rank difference\n(+ aSLE stronger, - cSLE stronger)"
    }
)

plt.title("Differential Cell–Cell Communication: aSLE vs cSLE")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# NETWORK PLOT

import networkx as nx

net_df = asle_stronger.head(30)

G = nx.DiGraph()

for _, row in net_df.iterrows():
    G.add_edge(
        row["source_aSLE"],
        row["target_aSLE"],
        weight=row["rank_difference"]
    )

plt.figure(figsize=(10, 10))

pos = nx.spring_layout(G, seed=42)

edges = G.edges(data=True)
weights = [d["weight"] for (_, _, d) in edges]

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2000,
    font_size=10,
    width=[w * 2 for w in weights]
)

plt.title("Top aSLE Cell–Cell Communication Network")
plt.show()

# BOTH DIRECTIONS IN ONE PLOT

top_csle = csle_stronger.head(20).copy()
top_csle["direction"] = "cSLE stronger"

top_asle = asle_stronger.head(20).copy()
top_asle["direction"] = "aSLE stronger"

combined = pd.concat([top_asle, top_csle])

combined["label"] = (
    combined["source_aSLE"].fillna(combined["source_cSLE"]) + " → " +
    combined["target_aSLE"].fillna(combined["target_cSLE"])
)

plt.figure(figsize=(10, 8))

sns.barplot(
    data=combined,
    y="label",
    x="abs_rank_difference",
    hue="direction"
)

plt.title("Differential Cell Communication (aSLE vs cSLE)")
plt.xlabel("Absolute Rank Difference")

plt.tight_layout()
plt.show()

import os
import pandas as pd

RESULTS_DIR = '/content/drive/MyDrive/GSE135779/Results'
fpath = os.path.join(RESULTS_DIR, 'cH_aSLE_comparison', 'cH_vs_aSLE_liana_merged.csv')
df = pd.read_csv(fpath)

# Check the situation first
print("Total rows:", len(df))
print("Shared:", (df['present_in_cH'] & df['present_in_aSLE']).sum())
print("cH only:", (df['present_in_cH'] & ~df['present_in_aSLE']).sum())
print("aSLE only:", (~df['present_in_cH'] & df['present_in_aSLE']).sum())

# Check for naming mismatches
print("\ncH source cell types:")
print(sorted(df['source_cH'].dropna().unique()))
print("\naSLE source cell types:")
print(sorted(df['source_aSLE'].dropna().unique()))

# Filter to shared only, rank by mean lrscore
df_shared = df[df['present_in_cH'] & df['present_in_aSLE']].copy()
df_shared['_ranking_score'] = df_shared[['lrscore_cH', 'lrscore_aSLE']].mean(axis=1)
top30 = df_shared.sort_values('_ranking_score', ascending=False).head(30).drop(columns=['_ranking_score'])

out_path = os.path.join(RESULTS_DIR, 'cH_aSLE_comparison', 'top30_cH_vs_aSLE_shared.csv')
top30.to_csv(out_path, index=False)
print(f"\nSaved {len(top30)} rows")
print(top30[['interaction_id', 'lrscore_cH', 'lrscore_aSLE', 'rank_diff_cH_minus_aSLE']].head(10).to_string())

