# -*- coding: utf-8 -*-
"""4_GSE135779_ALL_COMPARISON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJ3mlTyRBwTPahlX2ozZ6JpiIeNc1Tar
"""

import os
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

# -----------------------------
# 1. Set paths
# -----------------------------
base_dir = Path("/content/drive/MyDrive/GSE135779/Results/(cSLE-cH)-(aSLE-aH)_comparison")

csle_ch_file = base_dir / "/content/drive/MyDrive/GSE135779/Results/cH_cSLE_comparison/cH_vs_cSLE_liana_merged.csv"
asle_ah_file = base_dir / "/content/drive/MyDrive/GSE135779/Results/aH_aSLE_comparison/aH_vs_aSLE_liana_merged.csv"

out_file = base_dir / "age_dependent_disease_effect_heatmap.png"

# -----------------------------
# 2. Choose metric
# -----------------------------
# Good options: "expr_prod", "lr_means", "scaled_weight", "lrscore"
metric = "expr_prod"

# -----------------------------
# 3. Load data
# -----------------------------
csle_ch = pd.read_csv(csle_ch_file)
asle_ah = pd.read_csv(asle_ah_file)

print(csle_ch.shape, asle_ah.shape)
print(csle_ch.columns[:10])
print(asle_ah.columns[:10])

# -----------------------------
# 4. Prepare comparison tables
# -----------------------------
def prep_pairwise(df, healthy_label, sick_label, metric):
    source_h = f"source_{healthy_label}"
    target_h = f"target_{healthy_label}"
    ligand_h = f"ligand_complex_{healthy_label}"
    receptor_h = f"receptor_complex_{healthy_label}"
    metric_h = f"{metric}_{healthy_label}"

    source_s = f"source_{sick_label}"
    target_s = f"target_{sick_label}"
    ligand_s = f"ligand_complex_{sick_label}"
    receptor_s = f"receptor_complex_{sick_label}"
    metric_s = f"{metric}_{sick_label}"

    needed = [
        "interaction_id",
        source_h, target_h, ligand_h, receptor_h, metric_h,
        source_s, target_s, ligand_s, receptor_s, metric_s
    ]

    missing = [c for c in needed if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns: {missing}")

    out = pd.DataFrame({
        "interaction_id": df["interaction_id"],
        "source": df[source_s].fillna(df[source_h]),
        "target": df[target_s].fillna(df[target_h]),
        "ligand": df[ligand_s].fillna(df[ligand_h]),
        "receptor": df[receptor_s].fillna(df[receptor_h]),
        f"delta_{metric}_{sick_label}_minus_{healthy_label}": df[metric_s] - df[metric_h]
    })

    return out

child = prep_pairwise(
    csle_ch,
    healthy_label="cH",
    sick_label="cSLE",
    metric=metric
)

adult = prep_pairwise(
    asle_ah,
    healthy_label="aH",
    sick_label="aSLE",
    metric=metric
)

# -----------------------------
# 5. Calculate age-dependent disease effect
# -----------------------------
merged = child.merge(
    adult,
    on="interaction_id",
    how="inner",
    suffixes=("_child", "_adult")
)

child_delta = f"delta_{metric}_cSLE_minus_cH"
adult_delta = f"delta_{metric}_aSLE_minus_aH"

merged["age_dependent_effect"] = merged[child_delta] - merged[adult_delta]

merged["source"] = merged["source_child"]
merged["target"] = merged["target_child"]
merged["ligand"] = merged["ligand_child"]
merged["receptor"] = merged["receptor_child"]
merged["lr_pair"] = merged["ligand"] + " -> " + merged["receptor"]

print("Merged interactions:", merged.shape[0])

display(
    merged[
        [
            "interaction_id",
            "source",
            "target",
            "lr_pair",
            child_delta,
            adult_delta,
            "age_dependent_effect"
        ]
    ]
    .sort_values("age_dependent_effect", ascending=False)
    .head(30)
)

# -----------------------------
# 6. Source-target heatmap
# -----------------------------
heatmap_df = (
    merged
    .groupby(["source", "target"], as_index=False)["age_dependent_effect"]
    .mean()
)

heatmap_matrix = heatmap_df.pivot(
    index="source",
    columns="target",
    values="age_dependent_effect"
).fillna(0)

heatmap_matrix = heatmap_matrix.sort_index().sort_index(axis=1)

plt.figure(figsize=(12, 9))

vmax = np.nanmax(np.abs(heatmap_matrix.values))
if vmax == 0 or np.isnan(vmax):
    vmax = 1

sns.heatmap(
    heatmap_matrix,
    cmap="vlag",
    center=0,
    vmin=-vmax,
    vmax=vmax,
    linewidths=0.5,
    linecolor="lightgray",
    cbar_kws={
        "label": f"(cSLE - cH) - (aSLE - aH), {metric}"
    }
)

plt.title(f"Age-Dependent Disease Communication Effect\nMetric: {metric}")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(out_file, dpi=300, bbox_inches="tight")
plt.show()

print(f"Saved heatmap to: {out_file}")

# -----------------------------
# HEATMAP: Age-dependent disease effect
# Positive/red = stronger disease effect in cSLE
# Negative/blue = stronger disease effect in aSLE
# -----------------------------

heatmap_df = (
    merged
    .groupby(["source", "target"], as_index=False)["age_dependent_effect"]
    .mean()
)

heatmap_matrix = (
    heatmap_df
    .pivot(
        index="source",
        columns="target",
        values="age_dependent_effect"
    )
    .fillna(0)
)

plt.figure(figsize=(11, 8))

sns.heatmap(
    heatmap_matrix,
    cmap="coolwarm",
    center=0,
    linewidths=0.4,
    linecolor="gray",
    cbar_kws={
        "label": f"Mean age-dependent disease effect\n(+ cSLE stronger, - aSLE stronger)"
    }
)

plt.title("Age-Dependent Disease Communication Effect: (cSLE - cH) - (aSLE - aH)")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from pathlib import Path

base_dir = Path("/content/drive/MyDrive/GSE135779/Results")

files = {
    "cH": base_dir / "cH_liana/cH_liana_res.csv",
    "cSLE": base_dir / "cSLE_liana/cSLE_liana_res.csv",
    "aH": base_dir / "aH_liana/aH_liana_res.csv",
    "aSLE": base_dir / "aSLE_liana/aSLE_liana_res.csv",
}

metric = "expr_prod"

def load_liana_file(path, cohort, metric):
    df = pd.read_csv(path)

    needed = ["source", "target", "ligand_complex", "receptor_complex", metric]
    missing = [c for c in needed if c not in df.columns]
    if missing:
        raise ValueError(f"{cohort} is missing columns: {missing}")

    out = df[needed].copy()

    out["interaction_id"] = (
        out["source"].astype(str) + "|" +
        out["target"].astype(str) + "|" +
        out["ligand_complex"].astype(str) + "|" +
        out["receptor_complex"].astype(str)
    )

    out = out.rename(columns={
        "source": f"source_{cohort}",
        "target": f"target_{cohort}",
        "ligand_complex": f"ligand_{cohort}",
        "receptor_complex": f"receptor_{cohort}",
        metric: f"{metric}_{cohort}"
    })

    return out

dfs = {
    cohort: load_liana_file(path, cohort, metric)
    for cohort, path in files.items()
}

merged = dfs["cH"]

for cohort in ["cSLE", "aH", "aSLE"]:
    merged = merged.merge(
        dfs[cohort],
        on="interaction_id",
        how="outer"
    )

for cohort in ["cH", "cSLE", "aH", "aSLE"]:
    merged[f"{metric}_{cohort}"] = merged[f"{metric}_{cohort}"].fillna(0)

def first_nonnull(row, cols):
    for c in cols:
        if pd.notna(row.get(c)):
            return row[c]
    return np.nan

merged["source"] = merged.apply(
    lambda r: first_nonnull(r, [f"source_{x}" for x in ["cSLE", "cH", "aSLE", "aH"]]),
    axis=1
)

merged["target"] = merged.apply(
    lambda r: first_nonnull(r, [f"target_{x}" for x in ["cSLE", "cH", "aSLE", "aH"]]),
    axis=1
)

merged["ligand"] = merged.apply(
    lambda r: first_nonnull(r, [f"ligand_{x}" for x in ["cSLE", "cH", "aSLE", "aH"]]),
    axis=1
)

merged["receptor"] = merged.apply(
    lambda r: first_nonnull(r, [f"receptor_{x}" for x in ["cSLE", "cH", "aSLE", "aH"]]),
    axis=1
)

merged["lr_pair"] = merged["ligand"].astype(str) + "-" + merged["receptor"].astype(str)

merged["child_disease_effect"] = merged[f"{metric}_cSLE"] - merged[f"{metric}_cH"]
merged["adult_disease_effect"] = merged[f"{metric}_aSLE"] - merged[f"{metric}_aH"]

merged["age_dependent_effect"] = (
    merged["child_disease_effect"] -
    merged["adult_disease_effect"]
)

merged["abs_age_dependent_effect"] = merged["age_dependent_effect"].abs()

merged["direction"] = np.where(
    merged["age_dependent_effect"] > 0,
    "cSLE-skewed",
    np.where(
        merged["age_dependent_effect"] < 0,
        "aSLE-skewed",
        "No difference"
    )
)

top30 = (
    merged
    .sort_values("abs_age_dependent_effect", ascending=False)
    [
        [
            "direction",
            "source",
            "target",
            "ligand",
            "receptor",
            "lr_pair",
            f"{metric}_cH",
            f"{metric}_cSLE",
            f"{metric}_aH",
            f"{metric}_aSLE",
            "child_disease_effect",
            "adult_disease_effect",
            "age_dependent_effect",
            "abs_age_dependent_effect",
            "interaction_id"
        ]
    ]
    .head(30)
)

display(top30)

out_dir = Path("/content/drive/MyDrive/GSE135779/Results/(cSLE-cH)-(aSLE-aH)_comparison")
out_dir.mkdir(parents=True, exist_ok=True)

out_file = out_dir / f"top30_age_dependent_interactions_{metric}.csv"
top30.to_csv(out_file, index=False)

print(f"Saved: {out_file}")

# -----------------------------
# 7. Get top 15 positive and top 15 negative interactions
# -----------------------------

result_cols = [
    "direction",
    "source",
    "target",
    "ligand",
    "receptor",
    "lr_pair",
    f"{metric}_cH",
    f"{metric}_cSLE",
    f"{metric}_aH",
    f"{metric}_aSLE",
    "child_disease_effect",
    "adult_disease_effect",
    "age_dependent_effect",
    "abs_age_dependent_effect",
    "interaction_id"
]

top15_positive = (
    merged
    .sort_values("age_dependent_effect", ascending=False)
    [result_cols]
    .head(15)
)

top15_negative = (
    merged
    .sort_values("age_dependent_effect", ascending=True)
    [result_cols]
    .head(15)
)

top30_split = pd.concat(
    [top15_positive, top15_negative],
    axis=0
).reset_index(drop=True)

display(top30_split)

# -----------------------------
# 8. Save outputs
# -----------------------------

out_dir = Path("/content/drive/MyDrive/GSE135779/Results/(cSLE-cH)-(aSLE-aH)_comparison")
out_dir.mkdir(parents=True, exist_ok=True)

positive_file = out_dir / f"top15_cSLE_skewed_age_dependent_interactions_{metric}.csv"
negative_file = out_dir / f"top15_aSLE_skewed_age_dependent_interactions_{metric}.csv"
combined_file = out_dir / f"top30_split_age_dependent_interactions_{metric}.csv"

top15_positive.to_csv(positive_file, index=False)
top15_negative.to_csv(negative_file, index=False)
top30_split.to_csv(combined_file, index=False)

print(f"Saved positive interactions: {positive_file}")
print(f"Saved negative interactions: {negative_file}")
print(f"Saved combined file: {combined_file}")

import pandas as pd
from pathlib import Path

out_dir = Path("/content/drive/MyDrive/GSE135779/Results/(cSLE-cH)-(aSLE-aH)_comparison")

input_file = out_dir / "top30_split_age_dependent_interactions_expr_prod.csv"

df = pd.read_csv(input_file)

# Columns to keep for researcher-facing summary table
keep_cols = [
    "direction",
    "source",
    "target",
    "lr_pair",
    "child_disease_effect",
    "adult_disease_effect",
    "age_dependent_effect"
]

summary_df = df[keep_cols].copy()

# Round numeric columns for readability
numeric_cols = [
    "child_disease_effect",
    "adult_disease_effect",
    "age_dependent_effect"
]

summary_df[numeric_cols] = summary_df[numeric_cols].round(2)

# Optional: rename columns for readability
summary_df = summary_df.rename(columns={
    "direction": "Direction",
    "source": "Source",
    "target": "Target",
    "lr_pair": "Ligand-Receptor",
    "child_disease_effect": "cSLE - cH",
    "adult_disease_effect": "aSLE - aH",
    "age_dependent_effect": "(cSLE-cH) - (aSLE-aH)"
})

# Save summary table
summary_file = out_dir / "summary_top30_age_dependent_interactions_expr_prod.csv"
summary_df.to_csv(summary_file, index=False)

print(f"Saved summary table: {summary_file}")

display(summary_df)



import pandas as pd
from pathlib import Path

out_dir = Path("/content/drive/MyDrive/GSE135779/Results/(cSLE-cH)-(aSLE-aH)_comparison")

# Use whichever trimmed file you created
input_file = out_dir / "summary_top30_age_dependent_interactions_expr_prod.csv"
# input_file = out_dir / "summary_top30_age_dependent_interactions_expr_prod.csv"

df = pd.read_csv(input_file)

# Check column names
print(df.columns.tolist())

# Split by Direction column
csle_df = df[df["Direction"] == "cSLE-skewed"].copy()
asle_df = df[df["Direction"] == "aSLE-skewed"].copy()

# Save
csle_file = out_dir / "summary_short_top15_cSLE_skewed_interactions_expr_prod.csv"
asle_file = out_dir / "summary_short_top15_aSLE_skewed_interactions_expr_prod.csv"

csle_df.to_csv(csle_file, index=False)
asle_df.to_csv(asle_file, index=False)

print(f"Saved cSLE-skewed table: {csle_file}")
print(f"Saved aSLE-skewed table: {asle_file}")

display(csle_df)
display(asle_df)