"""Publication sensitivity analyses for the primary age-by-disease model.

This script uses donor-level LIANA scores already generated by notebook 03B.
It evaluates a female-only cohort, formally checks whether a B1/B2-restricted
analysis is estimable, accounts for cell exclusions, and generates the primary
volcano and female-only comparison plots. Existing files produced by this
script are replaced on rerun.
"""

from __future__ import annotations

import gc
import json
import platform
import sys
from importlib.metadata import version
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.stats.multitest import multipletests


BASE_DIR = Path(__file__).resolve().parents[1]
RESULTS = BASE_DIR / "Results"
SEVERITY = RESULTS / "severity_analysis"
QC = RESULTS / "qc"
SENSITIVITY = RESULTS / "sensitivity_analysis"
SENSITIVITY.mkdir(parents=True, exist_ok=True)
MIN_PER_GROUP = 5


def load_scores() -> pd.DataFrame:
    specifications = {
        "cH": ("healthy", "pediatric"),
        "cSLE": ("SLE", "pediatric"),
        "aH": ("healthy", "adult"),
        "aSLE": ("SLE", "adult"),
    }
    frames = []
    for prefix, (condition, age_group) in specifications.items():
        frame = pd.read_csv(SEVERITY / f"{prefix}_per_patient_scores.csv")
        frame["condition"] = condition
        frame["age_group"] = age_group
        frames.append(frame)
    return pd.concat(frames, ignore_index=True)


def fit_interactions(data: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    records: list[dict] = []
    failures: list[dict] = []
    for interaction_id, group in data.groupby("interaction_id", sort=False):
        counts = group.groupby(["age_group", "condition"])["sample"].nunique()
        if len(counts) < 4 or (counts < MIN_PER_GROUP).any() or group["score"].std() == 0:
            continue
        try:
            model = smf.ols(
                'score ~ C(condition, Treatment(reference="healthy")) * '
                'C(age_group, Treatment(reference="adult"))',
                data=group,
            ).fit(cov_type="HC3")
            term = next(term for term in model.params.index if ":" in term)
            ci_low, ci_high = model.conf_int().loc[term]
            first = group.iloc[0]
            records.append(
                {
                    "interaction_id": interaction_id,
                    "source": first["source"],
                    "target": first["target"],
                    "ligand_complex": first["ligand_complex"],
                    "receptor_complex": first["receptor_complex"],
                    "interaction_coef": model.params[term],
                    "interaction_ci95_low": ci_low,
                    "interaction_ci95_high": ci_high,
                    "n_observations": int(model.nobs),
                    "r_squared": model.rsquared,
                    "condition_number": model.condition_number,
                    "interaction_p_value": model.pvalues[term],
                }
            )
        except Exception as exc:  # retain a transparent failure log
            failures.append(
                {
                    "interaction_id": interaction_id,
                    "error_type": type(exc).__name__,
                    "message": str(exc),
                }
            )
    result = pd.DataFrame(records)
    if not result.empty:
        result["fdr_q_value"] = multipletests(
            result["interaction_p_value"], method="fdr_bh"
        )[1]
        result = result.sort_values(["fdr_q_value", "interaction_p_value"])
    return result, pd.DataFrame(
        failures, columns=["interaction_id", "error_type", "message"]
    )


def write_exclusion_accounting() -> None:
    rows = []
    for cohort in ("child", "adult"):
        post = pd.read_csv(QC / f"{cohort}_postfilter_sample_qc.csv")
        retained = pd.read_csv(QC / f"{cohort}_sample_celltype_counts.csv")
        retained_by_sample = retained.groupby("sample")["n_cells"].sum()
        post = post.assign(
            retained_after_annotation=post["sample"].map(retained_by_sample).fillna(0).astype(int)
        )
        post["excluded_by_annotation"] = post["n_cells"] - post["retained_after_annotation"]
        post["excluded_fraction"] = post["excluded_by_annotation"] / post["n_cells"]
        post.insert(0, "cohort", cohort)
        rows.append(
            post[
                [
                    "cohort",
                    "sample",
                    "n_cells",
                    "retained_after_annotation",
                    "excluded_by_annotation",
                    "excluded_fraction",
                ]
            ]
        )
    detail = pd.concat(rows, ignore_index=True)
    detail.to_csv(QC / "annotation_exclusion_by_sample.csv", index=False)
    summary = (
        detail.groupby("cohort", as_index=False)
        .agg(
            donors=("sample", "nunique"),
            cells_before_annotation=("n_cells", "sum"),
            cells_retained=("retained_after_annotation", "sum"),
            cells_excluded=("excluded_by_annotation", "sum"),
        )
    )
    summary["excluded_fraction"] = (
        summary["cells_excluded"] / summary["cells_before_annotation"]
    )
    summary.to_csv(QC / "annotation_exclusion_summary.csv", index=False)


def write_adult_resolution_marker_check() -> None:
    """Summarize prespecified ISG/cDC panels across adult Leiden clusters."""
    marker_table = pd.read_csv(
        BASE_DIR
        / "Notebook_Outputs"
        / "01E_GSE135779_ADULT_CELLTYPE_LABELLING"
        / "marker_genes_all_clusters.csv"
    )
    cluster_map = pd.read_csv(QC / "adult_cluster_to_celltype_map.csv")
    cluster_map["cluster"] = cluster_map["cluster"].astype(str)
    marker_table["group"] = marker_table["group"].astype(str)
    panels = {
        "ISG": ["ISG15", "IFI6", "IFI44L", "MX1", "IFIT1", "IFIT3", "RSAD2", "OAS1"],
        "cDC": ["FCER1A", "CD1C", "CLEC10A", "CST3"],
    }
    rows = []
    for panel_name, genes in panels.items():
        subset = marker_table[marker_table["names"].isin(genes)].copy()
        for cluster, group in subset.groupby("group"):
            assigned = cluster_map.loc[cluster_map["cluster"].eq(cluster), "cell_type"]
            rows.append(
                {
                    "cluster": cluster,
                    "assigned_cell_type": assigned.iloc[0] if len(assigned) else "Unmapped",
                    "marker_panel": panel_name,
                    "n_markers_detected": group["names"].nunique(),
                    "mean_rank_score": group["scores"].mean(),
                    "mean_log2fc": group["logfoldchanges"].mean(),
                    "markers_with_positive_score": int((group["scores"] > 0).sum()),
                }
            )
    pd.DataFrame(rows).sort_values(
        ["marker_panel", "mean_rank_score"], ascending=[True, False]
    ).to_csv(QC / "adult_isg_cdc_marker_check.csv", index=False)


def write_runtime_manifest() -> None:
    manifest = {
        "analysis": "08_PUBLICATION_SENSITIVITY_ANALYSES",
        "python": platform.python_version(),
        "platform": platform.platform(),
        "packages": {
            package: version(package)
            for package in ["numpy", "pandas", "matplotlib", "statsmodels"]
        },
        "command": " ".join(sys.argv),
        "random_seed": None,
    }
    provenance = RESULTS / "provenance"
    provenance.mkdir(parents=True, exist_ok=True)
    (provenance / "08_PUBLICATION_SENSITIVITY_ANALYSES.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )


def write_cohort_characteristics(metadata: pd.DataFrame) -> None:
    rows = []
    for group_name, group in metadata.groupby("Groups", sort=False):
        age = pd.to_numeric(group["Age"], errors="coerce")
        sledai = pd.to_numeric(group["SLEDAI"], errors="coerce")
        rows.append(
            {
                "group": group_name,
                "n_donors": group["sample"].nunique(),
                "age_median": age.median(),
                "age_q1": age.quantile(0.25),
                "age_q3": age.quantile(0.75),
                "female_n": int(group["Gender"].eq("F").sum()),
                "male_n": int(group["Gender"].eq("M").sum()),
                "sledai_available_n": int(sledai.notna().sum()),
                "sledai_median": sledai.median() if sledai.notna().any() else np.nan,
                "sledai_q1": sledai.quantile(0.25) if sledai.notna().any() else np.nan,
                "sledai_q3": sledai.quantile(0.75) if sledai.notna().any() else np.nan,
                "batches": "; ".join(
                    f"{batch}:{count}"
                    for batch, count in group["Batch"].value_counts().sort_index().items()
                ),
            }
        )
    pd.DataFrame(rows).to_csv(QC / "cohort_characteristics_summary.csv", index=False)


def main() -> None:
    metadata = pd.read_csv(SEVERITY / "patient_clinical_metadata.csv")
    scores = load_scores().merge(
        metadata[["sample", "Gender", "Batch"]], on="sample", how="left", validate="many_to_one"
    )
    if scores[["Gender", "Batch"]].isna().any().any():
        raise ValueError("Some donor scores lack Gender or Batch metadata")

    feasibility = (
        metadata.assign(
            age_group=np.where(metadata["Groups"].str.startswith("c"), "pediatric", "adult"),
            condition=np.where(metadata["Groups"].str.contains("SLE"), "SLE", "healthy"),
        )
        .query("Batch in ['B1', 'B2']")
        .groupby(["age_group", "condition"], as_index=False)["sample"]
        .nunique()
        .rename(columns={"sample": "n_donors"})
    )
    feasibility["minimum_required"] = MIN_PER_GROUP
    feasibility["estimable"] = feasibility["n_donors"] >= MIN_PER_GROUP
    feasibility.to_csv(SENSITIVITY / "batch_B1_B2_feasibility.csv", index=False)

    female = scores[scores["Gender"].eq("F")].copy()
    female_result, female_failures = fit_interactions(female)
    female_result.to_csv(SENSITIVITY / "female_only_age_diseasestatus_interaction.csv", index=False)
    female_failures.to_csv(SENSITIVITY / "female_only_model_failures.csv", index=False)

    primary = pd.read_csv(SEVERITY / "age_diseasestatus_interaction.csv")
    comparison = primary[["interaction_id", "interaction_coef", "fdr_q_value"]].merge(
        female_result[["interaction_id", "interaction_coef", "fdr_q_value"]],
        on="interaction_id",
        suffixes=("_primary", "_female_only"),
    )
    primary_sig = comparison["fdr_q_value_primary"] < 0.05
    female_sig = comparison["fdr_q_value_female_only"] < 0.05
    summary = pd.DataFrame(
        [
            {
                "analysis": "primary_all_donors",
                "interactions_tested": len(primary),
                "fdr_below_0_05": int((primary["fdr_q_value"] < 0.05).sum()),
                "fdr_below_0_10": int((primary["fdr_q_value"] < 0.10).sum()),
            },
            {
                "analysis": "female_only",
                "interactions_tested": len(female_result),
                "fdr_below_0_05": int((female_result["fdr_q_value"] < 0.05).sum()),
                "fdr_below_0_10": int((female_result["fdr_q_value"] < 0.10).sum()),
            },
        ]
    )
    summary["shared_coefficients_pearson_r"] = np.nan
    summary["primary_fdr05_retained_in_female_only"] = np.nan
    correlation = np.nan
    if len(comparison) > 1:
        correlation = comparison["interaction_coef_primary"].corr(
            comparison["interaction_coef_female_only"]
        )
        retained = int((primary_sig & female_sig).sum())
        summary.loc[summary["analysis"].eq("female_only"), "shared_coefficients_pearson_r"] = correlation
        summary.loc[
            summary["analysis"].eq("female_only"),
            "primary_fdr05_retained_in_female_only",
        ] = retained
    summary.to_csv(SENSITIVITY / "primary_sensitivity_summary.csv", index=False)
    comparison.to_csv(SENSITIVITY / "primary_vs_female_only_comparison.csv", index=False)

    # Compare the estimated effects directly, rather than comparing only the
    # numbers of significant results. Highlight interactions significant in the
    # primary analysis and use equal axes so deviations from the identity line
    # are visually meaningful.
    primary_significant = comparison["fdr_q_value_primary"] < 0.05
    bounds = comparison[
        ["interaction_coef_primary", "interaction_coef_female_only"]
    ].to_numpy()
    axis_min = float(np.nanmin(bounds))
    axis_max = float(np.nanmax(bounds))
    padding = max((axis_max - axis_min) * 0.04, 0.01)
    axis_limits = (axis_min - padding, axis_max + padding)

    fig, ax = plt.subplots(figsize=(6.2, 6.0))
    ax.scatter(
        comparison.loc[~primary_significant, "interaction_coef_primary"],
        comparison.loc[~primary_significant, "interaction_coef_female_only"],
        s=10,
        alpha=0.3,
        color="#8c8c8c",
        linewidths=0,
        label="Primary FDR >= 0.05",
    )
    ax.scatter(
        comparison.loc[primary_significant, "interaction_coef_primary"],
        comparison.loc[primary_significant, "interaction_coef_female_only"],
        s=16,
        alpha=0.8,
        color="#2b6cb0",
        linewidths=0,
        label="Primary FDR < 0.05",
    )
    ax.plot(axis_limits, axis_limits, color="black", linestyle="--", linewidth=0.9)
    ax.axhline(0, color="#666666", linewidth=0.5)
    ax.axvline(0, color="#666666", linewidth=0.5)
    ax.set_xlim(axis_limits)
    ax.set_ylim(axis_limits)
    ax.set_aspect("equal", adjustable="box")
    ax.set(
        xlabel="Primary interaction coefficient (all donors)",
        ylabel="Female-only interaction coefficient",
        title=f"Female-only sensitivity analysis (Pearson r = {correlation:.3f})",
    )
    ax.legend(frameon=False, loc="upper left")
    fig.tight_layout()
    fig.savefig(
        SENSITIVITY / "primary_vs_female_only_coefficients.png",
        dpi=600,
        bbox_inches="tight",
        facecolor="white",
    )
    plt.close(fig)

    plot = primary.copy()
    plot["minus_log10_fdr"] = -np.log10(plot["fdr_q_value"].clip(lower=np.finfo(float).tiny))
    significant = plot["fdr_q_value"] < 0.05
    fig, ax = plt.subplots(figsize=(7.2, 5.2))
    ax.scatter(
        plot.loc[~significant, "interaction_coef"],
        plot.loc[~significant, "minus_log10_fdr"],
        s=9,
        alpha=0.3,
        color="#8c8c8c",
        linewidths=0,
        label="FDR ≥ 0.05",
    )
    ax.scatter(
        plot.loc[significant, "interaction_coef"],
        plot.loc[significant, "minus_log10_fdr"],
        s=13,
        alpha=0.8,
        color="#a83232",
        linewidths=0,
        label="FDR < 0.05",
    )
    ax.axhline(-np.log10(0.05), color="black", linestyle="--", linewidth=0.8)
    ax.axvline(0, color="black", linewidth=0.7)
    ax.set(
        xlabel="Age-group × SLE interaction coefficient",
        ylabel="−log10(FDR)",
        title=f"Primary donor-level interaction test ({significant.sum()}/{len(plot)} at FDR < 0.05)",
    )
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(SEVERITY / "primary_age_diseasestatus_volcano.png", dpi=600, bbox_inches="tight")
    plt.close(fig)

    significant_table = primary[primary["fdr_q_value"] < 0.05].copy()
    significant_table["direction"] = np.where(
        significant_table["interaction_coef"] > 0,
        "more positive SLE-associated change in pediatric cohort",
        "more negative SLE-associated change in pediatric cohort",
    )
    significant_table.to_csv(SEVERITY / "primary_significant_interactions_fdr05.csv", index=False)
    write_exclusion_accounting()
    write_adult_resolution_marker_check()
    write_cohort_characteristics(metadata)
    write_runtime_manifest()
    gc.collect()
    print(summary.to_string(index=False))
    print("B1/B2 feasibility:\n", feasibility.to_string(index=False))


if __name__ == "__main__":
    main()
